// src/lib/indiaLocationData.ts
// State → Districts → Sub-districts (Talukas/Tehsils/Mandals)

export type LocationData = {
    [state: string]: {
        [district: string]: string[]
    }
}

export const INDIA_LOCATION_DATA: LocationData = {
    "Andhra Pradesh": {
        "Anantapur": ["Anantapur", "Dharmavaram", "Guntakal", "Hindupur", "Kadiri", "Kalyanadurgam", "Rayadurgam", "Tadipatri", "Uravakonda"],
        "Chittoor": ["Chittoor", "Kuppam", "Madanapalle", "Nagari", "Punganur", "Tirupati", "Srikalahasti"],
        "East Godavari": ["Amalapuram", "Kakinada", "Peddapuram", "Rajahmundry", "Ramachandrapuram", "Mandapeta"],
        "Guntur": ["Bapatla", "Gurazala", "Guntur", "Macherla", "Narasaraopet", "Palnadu", "Sattenapalle"],
        "Krishna": ["Gudivada", "Machilipatnam", "Nandigama", "Nuzvid", "Vijayawada"],
        "Kurnool": ["Adoni", "Alur", "Atmakur", "Kodumur", "Kurnool", "Nandyal", "Pattikonda"],
        "Nellore": ["Atmakur", "Gudur", "Kavali", "Nellore", "Sullurpeta", "Venkatagiri"],
        "Prakasam": ["Chirala", "Darsi", "Giddalur", "Kanigiri", "Markapur", "Ongole", "Podili"],
        "Srikakulam": ["Amadalavalasa", "Ichapuram", "Narasannapeta", "Palakonda", "Rajam", "Srikakulam"],
        "Visakhapatnam": ["Bheemunipatnam", "Narsipatnam", "Paderu", "Visakhapatnam"],
        "Vizianagaram": ["Bobbili", "Cheepurupalli", "Parvathipuram", "Salur", "Vizianagaram"],
        "West Godavari": ["Bhimavaram", "Eluru", "Narsapur", "Palacole", "Tanuku", "Undi"],
        "YSR Kadapa": ["Badvel", "Jammalamadugu", "Kadapa", "Mydukur", "Proddatur", "Pulivendla", "Rajampet"],
    },
    "Arunachal Pradesh": {
        "Anjaw": ["Hawai", "Manchal"],
        "Changlang": ["Bordumsa", "Changlang", "Kharsang", "Miao", "Nampong"],
        "Dibang Valley": ["Anini"],
        "East Kameng": ["Bameng", "Seppa"],
        "East Siang": ["Boleng", "Mebo", "Nari", "Pasighat", "Ruksin"],
        "Kamle": ["Raga"],
        "Kra Daadi": ["Palin"],
        "Kurung Kumey": ["Koloriang"],
        "Lepa Rada": ["Basar"],
        "Lohit": ["Namsai", "Tezu"],
        "Longding": ["Longding", "Pumao"],
        "Lower Dibang Valley": ["Roing"],
        "Lower Siang": ["Likabali"],
        "Lower Subansiri": ["Ziro"],
        "Namsai": ["Chongkham", "Namsai"],
        "Pakke Kessang": ["Seijosa"],
        "Papum Pare": ["Balijan", "Doimukh", "Itanagar", "Sagalee"],
        "Shi Yomi": ["Mechuka"],
        "Siang": ["Boleng"],
        "Tawang": ["Tawang"],
        "Tirap": ["Deomali", "Khonsa"],
        "Upper Dibang Valley": ["Anini"],
        "Upper Siang": ["Mariyang", "Yingkiong"],
        "Upper Subansiri": ["Daporijo"],
        "West Kameng": ["Bomdila", "Dirang"],
        "West Siang": ["Aalo", "Mechuka"],
    },
    "Assam": {
        "Baksa": ["Barama", "Baska", "Dhamdhama", "Goreswar", "Mushalpur", "Nagrijuli", "Tamulpur"],
        "Barpeta": ["Barpeta", "Barpeta Road", "Chenga", "Howly", "Mandia", "Sarupeta", "Sarthebari"],
        "Biswanath": ["Biswanath Chariali", "Gohpur", "Sootea"],
        "Bongaigaon": ["Bongaigaon", "Borobazar", "Manikpur", "Sidli"],
        "Cachar": ["Badarpur", "Katigorah", "Lakhipur", "Silchar", "Sonai", "Udharbond"],
        "Charaideo": ["Amguri", "Sonari"],
        "Chirang": ["Bijni", "Borobazar", "Chirang", "Runikhata"],
        "Darrang": ["Dalgaon", "Kalaigaon", "Mangaldoi", "Patacharkuchi", "Sipajhar"],
        "Dhemaji": ["Dhemaji", "Jonai", "Machkhowa", "Silapathar"],
        "Dhubri": ["Agomani", "Bilasipara", "Chapar", "Dhubri", "Gauripur", "Golokganj"],
        "Dibrugarh": ["Dibrugarh", "Joypur", "Khowang", "Lahowal", "Moran", "Naharkatia", "Tingkhong"],
        "Dima Hasao": ["Haflong", "Mahur"],
        "Goalpara": ["Balijana", "Dudhnoi", "Goalpara", "Krishnai", "Lakhipur"],
        "Golaghat": ["Golaghat", "Khumtai", "Sarupathar", "Tsaleka"],
        "Hailakandi": ["Algapur", "Hailakandi", "Katlicherra", "Lala"],
        "Hojai": ["Hojai", "Lumding"],
        "Jorhat": ["Jorhat", "Mariani", "Titabor", "Teok"],
        "Kamrup": ["Boko", "Chamaria", "Chaygaon", "Goroimari", "Hajo", "Kamalpur", "Nagarbera", "Palashbari", "Rangia", "Rani"],
        "Kamrup Metropolitan": ["Amingaon", "Azara", "Chandrapur", "Dispur", "Guwahati", "Jalukbari", "Sonapur"],
        "Karbi Anglong": ["Bokajan", "Diphu", "Hamren", "Howraghat", "Koloabari"],
        "Karimganj": ["Badarpur", "Karimganj", "Nilambazar", "Patharkandi", "Ratabari"],
        "Kokrajhar": ["Bijni", "Gossaigaon", "Kokrajhar", "Parbatjhora"],
        "Lakhimpur": ["Bihpuria", "Dhakuakhana", "Lakhimpur", "Narayanpur", "Nowboicha"],
        "Majuli": ["Majuli"],
        "Morigaon": ["Laharighat", "Mayong", "Morigaon"],
        "Nagaon": ["Batadrava", "Dhing", "Doboka", "Hojai", "Kaliabor", "Kampur", "Nagaon", "Raha", "Rupahi"],
        "Nalbari": ["Barbhag", "Barkhetri", "Ghograpar", "Nalbari", "Tihu"],
        "Sivasagar": ["Amguri", "Charaideo", "Demow", "Gaurisagar", "Nazira", "Sivasagar"],
        "Sonitpur": ["Biswanath Chariali", "Borgolai", "Dhekiajuli", "Gohpur", "Missamari", "Rangapara", "Tezpur"],
        "South Salmara-Mankachar": ["Mankachar", "South Salmara"],
        "Tinsukia": ["Digboi", "Doom Dooma", "Margherita", "Sadiya", "Tinsukia"],
        "Udalguri": ["Bhergaon", "Dimakuchi", "Kalaigaon", "Udalguri"],
        "West Karbi Anglong": ["Baithalangso", "Raha"],
    },
    "Bihar": {
        "Araria": ["Araria", "Forbesganj", "Jokihat", "Kursakanta", "Narpatganj", "Palasi", "Raniganj", "Sikti"],
        "Arwal": ["Arwal", "Kaler", "Kurtha", "Sonbhadra Banshi Suryapur"],
        "Aurangabad": ["Aurangabad", "Barun", "Daudnagar", "Deo", "Goh", "Haspura", "Kutumba", "Madanpur", "Nabinagar", "Obra", "Rafiganj"],
        "Banka": ["Amarpur", "Barahat", "Banka", "Belhar", "Bounsi", "Chanan", "Dhuraiya", "Fullidumar", "Katoria", "Rajoun", "Shambhuganj"],
        "Begusarai": ["Bachhwara", "Barauni", "Begusarai", "Bhagwanpur", "Birpur", "Balia", "Cheria Bariarpur", "Dandari", "Garhpura", "Mansurchak", "Matihani", "Nawkothi", "Sahebpur Kamal", "Samho"],
        "Bhagalpur": ["Bhagalpur", "Bihpur", "Goradih", "Jagdishpur", "Kahalgaon", "Kharik", "Naugachhia", "Pirpainti", "Sabour", "Sanhaula", "Shahkund", "Sultanganj"],
        "Bhojpur": ["Agiaon", "Ara", "Arrah", "Barhara", "Behea", "Bigha", "Charpokhari", "Garhani", "Jagdishpur", "Koilwar", "Piro", "Sandesh", "Sahar", "Shahpur", "Tarari", "Udwantnagar"],
        "Buxar": ["Buxar", "Chausa", "Dumraon", "Itarhi", "Rajpur", "Simri"],
        "Darbhanga": ["Alinagar", "Baheri", "Bahadurpur", "Benipur", "Biraul", "Darbhanga", "Ghanshyampur", "Hanuman Nagar", "Hayaghat", "Jale", "Keoti", "Kiratpur", "Kusheshwar Asthan", "Manigachhi", "Singhwara", "Tardih"],
        "East Champaran": ["Adapur", "Areraj", "Banjaria", "Bankatwa", "Chakia", "Dhaka", "Ghorasahan", "Harsidhi", "Kesaria", "Kotwa", "Motihari", "Pakaridayal", "Patahi", "Phenhara", "Pipra", "Raxaul", "Sangrampur", "Sugauli", "Tetaria", "Turkaulia"],
        "Gaya": ["Amas", "Atri", "Barachatti", "Belaganj", "Bodh Gaya", "Dobhi", "Dungeswari", "Fatehpur", "Gaya", "Guraru", "Imamganj", "Khizarsarai", "Konch", "Manpur", "Mohanpur", "Paraiya", "Sherghati", "Tankuppa", "Tekari", "Wazirganj"],
        "Gopalganj": ["Barauli", "Bhore", "Bhorey", "Gopalganj", "Hathua", "Kuchaikot", "Manjha", "Phulwaria", "Sidhwalia", "Thawe", "Uchkagaon", "Vijayipur"],
        "Jamui": ["Barhat", "Chakai", "Gidhaur", "Islamnagar", "Jamui", "Jhajha", "Khaira", "Lachhipur", "Sikandra", "Sono"],
        "Jehanabad": ["Ghoshi", "Hulasganj", "Jehanabad", "Kako", "Makhdumpur", "Modanganj", "Ratni Faridpur"],
        "Kaimur": ["Adhaura", "Bhagwanpur", "Bhabua", "Chainpur", "Chand", "Durgawati", "Kudra", "Mohammad Pur", "Nuaon", "Ramgarh", "Rampur"],
        "Katihar": ["Amdabad", "Azamnagar", "Balrampur", "Barari", "Barsoi", "Dandkhora", "Falka", "Hasanganj", "Kadwa", "Katihar", "Korha", "Manihari", "Mansahi", "Pranpur", "Sameli"],
        "Khagaria": ["Alauli", "Chautham", "Gogri", "Khagaria", "Mansi", "Mansi Hajipur", "Parbalpur"],
        "Kishanganj": ["Bahadurganj", "Dighalbank", "Kochadhaman", "Pothia", "Terhagachh", "Thakurganj"],
        "Lakhisarai": ["Barahiya", "Halsi", "Lakhisarai", "Pipariya", "Ramgarh Chowk", "Surajgarha"],
        "Madhepura": ["Alamnagar", "Bihariganj", "Chausa", "Gamharia", "Ghailarh", "Gwalpara", "Kumarkhand", "Madhepura", "Murliganj", "Puraini", "Shankarpur", "Singheshwar", "Udakishanganj"],
        "Madhubani": ["Andharatharhi", "Babubarhi", "Basopatti", "Benipatti", "Bisfi", "Ghoghardiha", "Harlakhi", "Jaynagar", "Jhanjharpur", "Khajauli", "Ladania", "Laukaha", "Laukahi", "Madhubani", "Pandaul", "Phulparas", "Rajnagar", "Rahika"],
        "Munger": ["Asarganj", "Bariyarpur", "Dharhara", "Jamalpur", "Kharagpur", "Mufassil", "Munger", "Sangrampur", "Tarapur", "Tetia Bambar"],
        "Muzaffarpur": ["Aurai", "Bochaha", "Gaighat", "Kanti", "Katra", "Kurhani", "Maniyari", "Marwan", "Minapur", "Motipur", "Muzaffarpur", "Paru", "Sahebganj", "Sakra", "Saraiya", "Sikandarpur"],
        "Nalanda": ["Asthawan", "Ben", "Bihar Sharif", "Chandi", "Ekangarsarai", "Giriak", "Harnaut", "Hilsa", "Islampur", "Katrisarai", "Nalanda", "Noorsarai", "Parbalpur", "Rahui", "Rajgir", "Silao", "Sirmera", "Tharthari"],
        "Nawada": ["Akbarpur", "Gobindpur", "Hisua", "Kawakol", "Kashi Chak", "Meskaur", "Nawada", "Nardiganj", "Pakribarawan", "Rajauli", "Roh", "Sirdala", "Warsaliganj"],
        "Patna": ["Athmalgola", "Bakhtiyarpur", "Barh", "Belchi", "Bihta", "Bikram", "Danapur", "Dhanarua", "Dulhin Bazar", "Fatuha", "Ghoswari", "Khusrupur", "Maner", "Masaurhi", "Mokama", "Naubatpur", "Pandarak", "Paliganj", "Patna Sadar", "Phulwari", "Punpun", "Sampatchak"],
        "Purnia": ["Amour", "Baisi", "Banmankhi", "Bhawanipur", "Byasi", "Dagarua", "Dhamdaha", "Jalalgarh", "Kasba", "Krityanand Nagar", "Purnia"],
        "Rohtas": ["Akorhigola", "Bikramganj", "Chenari", "Dawath", "Dinara", "Kargahar", "Naohatta", "Nokha", "Rohtas", "Sanjhauli", "Sasaram", "Shivsagar", "Suryapura", "Tilouthu"],
        "Saharsa": ["Bangaon", "Kahara", "Mahishi", "Nauhatta", "Patarghat", "Saharsa", "Sattar Kataha", "Salkhua", "Sour Bazar"],
        "Samastipur": ["Bibhutipur", "Bithan", "Dalsinghsarai", "Hasanpur", "Kalyanpur", "Mohiuddinagar", "Morwa", "Patori", "Pusa", "Rosera", "Samastipur", "Shivajinagar", "Singhia", "Tajpur", "Ujiyarpur", "Vidyapati Nagar", "Wahidpur", "Warisnagar"],
        "Saran": ["Amnour", "Chapra", "Dariauon", "Dariapur", "Ekma", "Garkha", "Ishuapur", "Jalalpur", "Lahladpur", "Maker", "Manjhi", "Marhaura", "Mashrakh", "Marhowra", "Nagra", "Panapur", "Parsa", "Revelganj", "Sonepur", "Taraiya"],
        "Sheikhpura": ["Ariari", "Barbigha", "Chewara", "Sheikhpura", "Shekhopur Sarai"],
        "Sheohar": ["Piprahi", "Sheohar", "Tariyani"],
        "Sitamarhi": ["Bajpatti", "Bathnaha", "Belsand", "Dumra", "Majorganj", "Nanpur", "Parihar", "Pupri", "Runnisaidpur", "Sitamarhi", "Sursand"],
        "Siwan": ["Andar", "Barharia", "Basantpur", "Bhagwanpur Hat", "Darauli", "Daraundha", "Goriakothi", "Hussainganj", "Lakri Nabiganj", "Maharajganj", "Mairwa", "Nautan", "Pachrukhi", "Raghunathpur", "Siswan", "Siwan", "Ziradei"],
        "Supaul": ["Birpur", "Chhatapur", "Kishanpur", "Nirmali", "Pipra", "Pratapganj", "Raghopur", "Supaul", "Triveniganj"],
        "Vaishali": ["Bhagwanpur", "Bidupur", "Chehrakala", "Desari", "Goraul", "Hajipur", "Jandaha", "Lalganj", "Mahua", "Mahnar", "Mahuar", "Patepur", "Pahnapur", "Raja Pakar", "Raghopur", "Sahdei Buzurg", "Vaishali", "Vaishali Nagar"],
        "West Champaran": ["Bagaha", "Bettiah", "Chanpatia", "Gaunaha", "Jogapatti", "Lauriya", "Mainatand", "Nautan", "Narkatiaganj", "Piprasi", "Ramnagar", "Shikarganj", "Sikta"],
    },
    "Chhattisgarh": {
        "Balod": ["Balod", "Dondi", "Dondi Lohara", "Gurur"],
        "Baloda Bazar": ["Baloda Bazar", "Bhatapara", "Kasadol", "Palari", "Simga"],
        "Balrampur": ["Balrampur", "Rajpur", "Ramanujganj", "Shankargarh", "Wadrafnagar"],
        "Bastar": ["Bastar", "Darbha", "Jagdalpur", "Lohandiguda", "Tokapal"],
        "Bemetara": ["Bemetara", "Berla", "Nandini Nagar", "Nawagarh", "Saja"],
        "Bijapur": ["Bhairamgarh", "Bijapur", "Bhopalpatnam", "Usur"],
        "Bilaspur": ["Bilaspur", "Bilha", "Gaurela", "Kota", "Lormi", "Mungeli", "Pendra", "Takhatpur"],
        "Dantewada": ["Dantewada", "Geedam", "Katekalyan", "Kuakonda"],
        "Dhamtari": ["Dhamtari", "Kurud", "Magarlod", "Nagri"],
        "Durg": ["Bhilai", "Durg", "Patan"],
        "Gariaband": ["Chhura", "Deobhog", "Fingeshwar", "Gariaband", "Mainpur"],
        "Gaurela Pendra Marwahi": ["Gaurela", "Marwahi", "Pendra"],
        "Janjgir-Champa": ["Akaltara", "Bamphard", "Champa", "Jaijaipur", "Janjgir", "Malkharoda", "Naila Janjgir", "Pamgarh", "Sakti"],
        "Jashpur": ["Bagicha", "Duldula", "Jashpur", "Kunkuri", "Manora", "Pathalgaon"],
        "Kabirdham": ["Bodla", "Kabirdham", "Pandariya", "Sahaspur Lohara"],
        "Kanker": ["Antagarh", "Bhanupratappur", "Charama", "Kanker", "Narharpur", "Pakhanjore"],
        "Kondagaon": ["Baderaajpur", "Farsgaon", "Kondagaon", "Makdi"],
        "Korba": ["Kartala", "Katghora", "Korba", "Pali", "Podi Uproda"],
        "Koriya": ["Baikunthpur", "Bharatpur", "Manendragarh", "Sonhat"],
        "Mahasamund": ["Bagbahra", "Basna", "Mahasamund", "Pithora", "Saraipali"],
        "Mungeli": ["Lormi", "Mungeli", "Patharia"],
        "Narayanpur": ["Narayanpur", "Orchha"],
        "Raigarh": ["Chakradhar Nagar", "Dharamjaigarh", "Ghargoda", "Kharsia", "Lailunga", "Raigarh", "Sarangarh", "Tamnar"],
        "Raipur": ["Arang", "Abhanpur", "Dharsiwa", "Raipur", "Tilda Newra"],
        "Rajnandgaon": ["Chuikhadan", "Dongargarh", "Khairagarh", "Mohla", "Rajnandgaon"],
        "Sukma": ["Chhindgarh", "Konta", "Sukma"],
        "Surajpur": ["Bhaiyathan", "Pratapur", "Ramanujanagar", "Surajpur"],
        "Surguja": ["Ambikapur", "Batauli", "Lakhanpur", "Lundra", "Mainpat", "Odgi", "Pratappur", "Sitapur", "Udaipur"],
    },
    "Goa": {
        "North Goa": ["Bardez", "Bicholim", "Pernem", "Ponda", "Sattari", "Tiswadi"],
        "South Goa": ["Canacona", "Dharbandora", "Mormugao", "Quepem", "Salcete", "Sanguem"],
    },
    "Gujarat": {
        "Ahmedabad": ["Ahmedabad City", "Bavla", "Daskroi", "Detroj-Rampura", "Dhandhuka", "Dholka", "Mandal", "Sanand", "Viramgam"],
        "Amreli": ["Amreli", "Babra", "Bagasara", "Dhari", "Jafrabad", "Kunkavav Vadia", "Lathi", "Liliya", "Rajula", "Saverkundla"],
        "Anand": ["Anand", "Anklav", "Borsad", "Cambay", "Khambhat", "Petlad", "Sojitra", "Tarapur", "Umreth"],
        "Aravalli": ["Bayad", "Bhiloda", "Dhansura", "Malpur", "Meghraj", "Modasa"],
        "Banaskantha": ["Amirgadh", "Bhabhar", "Danta", "Dantiwada", "Deodar", "Kankrej", "Lakhani", "Palanpur", "Suigam", "Tharad", "Vadgam", "Vav"],
        "Bharuch": ["Amod", "Ankleshwar", "Bharuch", "Hansot", "Jambusar", "Jhagadia", "Netrang", "Vagra", "Valia"],
        "Bhavnagar": ["Bhavnagar", "Gariadhar", "Ghogha", "Jesar", "Mahuva", "Palitana", "Sihor", "Talaja", "Umarala", "Vallabhipur"],
        "Botad": ["Barwala", "Botad", "Gadhada", "Ranpur"],
        "Chhota Udaipur": ["Bodeli", "Chhota Udaipur", "Jetpur Pavi", "Kavant", "Nasvadi", "Pavi Jetpur", "Sankheda"],
        "Dahod": ["Dahod", "Devgadh Baria", "Dhanpur", "Fatepura", "Garbada", "Jhalod", "Limkheda", "Sanjeli", "Zalod"],
        "Dang": ["Ahwa", "Subir", "Waghai"],
        "Devbhoomi Dwarka": ["Bhanvad", "Dwarka", "Kalyanpur", "Khambhalia"],
        "Gandhinagar": ["Dahegam", "Dehgam", "Gandhinagar", "Kalol", "Mansa"],
        "Gir Somnath": ["Kodinar", "Patan (Veraval)", "Sutrapada", "Talala", "Una", "Veraval"],
        "Jamnagar": ["Dhrol", "Jamjodhpur", "Jamnagar", "Jodia", "Kalavad", "Lalpur"],
        "Junagadh": ["Bantva Manavadar", "Junagadh", "Keshod", "Maliya Hatina", "Mangrol", "Mendarda", "Vanthali", "Visavadar"],
        "Kheda": ["Capadvanj", "Kathlal", "Kheda", "Matar", "Mehmedabad", "Nadiad", "Thasra", "Vagad", "Virpur"],
        "Kutch": ["Abdasa", "Anjar", "Bhachau", "Bhuj", "Dayapar", "Dudhai", "Gandhinagar (Kutch)", "Lakhpat", "Mandvi", "Mundra", "Nakhatrana", "Rapar"],
        "Mahisagar": ["Balasinor", "Khanpur", "Lunawada", "Santrampur", "Virpur"],
        "Mehsana": ["Becharaji", "Kadi", "Kheralu", "Mehsana", "Satlasana", "Unjha", "Vadnagar", "Vijapur", "Visnagar"],
        "Morbi": ["Halvad", "Maliya", "Morbi", "Tankara", "Wankaner"],
        "Narmada": ["Dediapada", "Garudeshwar", "Nandod", "Sagbara", "Tilakwada"],
        "Navsari": ["Chikhli", "Gandevi", "Jalalpore", "Khergam", "Navsari", "Vansda"],
        "Panchmahal": ["Ghoghamba", "Godhra", "Halol", "Jambughoda", "Kalol", "Lunawada", "Morva Hadaf", "Shehera"],
        "Patan": ["Chanasma", "Harij", "Patan", "Radhanpur", "Sami", "Santalpur", "Saraswati", "Sidhpur"],
        "Porbandar": ["Kutiyana", "Porbandar", "Ranavav"],
        "Rajkot": ["Dhoraji", "Gondal", "Jasdan", "Jetpur", "Kotda Sangani", "Lodhika", "Paddhari", "Rajkot", "Tankara", "Upleta", "Vinchhiya", "Wankaner"],
        "Sabarkantha": ["Bayad", "Himmatnagar", "Idar", "Khedbrahma", "Meghraj", "Prantij", "Talod", "Vadali", "Vijaynagar"],
        "Surat": ["Bardoli", "Choryasi", "Kamrej", "Mahuva", "Mandvi", "Mangrol", "Olpad", "Palsana", "Surat City", "Umarpada"],
        "Surendranagar": ["Chuda", "Chotila", "Dasada", "Dhrangadhra", "Halvad", "Lakhtar", "Limbdi", "Muli", "Sayla", "Thangadh", "Wadhwan"],
        "Tapi": ["Nizar", "Songadh", "Uchchhal", "Valod", "Vyara"],
        "Vadodara": ["Chhota Udaipur", "Dabhoi", "Desar", "Karjan", "Padra", "Savli", "Shinor", "Vadodara City", "Vaghodia"],
        "Valsad": ["Dharampur", "Kaprada", "Pardi", "Umbergaon", "Valsad", "Vapi"],
    },
    "Haryana": {
        "Ambala": ["Ambala", "Barara", "Naraingarh", "Mullana", "Saha", "Shahzadpur"],
        "Bhiwani": ["Badhra", "Bhiwani", "Bawani Khera", "Kairu", "Loharu", "Siwani", "Tosham"],
        "Charkhi Dadri": ["Badhra", "Charkhi Dadri", "Jhojhu Kalan"],
        "Faridabad": ["Ballabhgarh", "Faridabad"],
        "Fatehabad": ["Bhuna", "Fatehabad", "Jakhal", "Ratia", "Tohana"],
        "Gurugram": ["Gurugram", "Pataudi", "Sohna"],
        "Hisar": ["Adampur", "Agroha", "Barwala", "Hansi", "Hisar", "Narnaund", "Uklana"],
        "Jhajjar": ["Bahadurgarh", "Beri", "Jhajjar", "Machhrauli", "Matanhail", "Salhawas"],
        "Jind": ["Jind", "Julana", "Narwana", "Pillukhera", "Safidon", "Uchana"],
        "Kaithal": ["Guhla", "Kaithal", "Kalayat", "Pundri", "Rajound", "Siwan"],
        "Karnal": ["Assandh", "Gharaunda", "Indri", "Karnal", "Nilokheri"],
        "Kurukshetra": ["Babain", "Ismailabad", "Ladwa", "Pehowa", "Shahabad", "Thanesar"],
        "Mahendragarh": ["Ateli Mandi", "Kanina", "Mahendragarh", "Narnaul", "Nangal Chaudhry"],
        "Mewat": ["Ferozepur Jhirka", "Nagina", "Nuh", "Punahana", "Tauru"],
        "Palwal": ["Hathin", "Hodal", "Palwal"],
        "Panchkula": ["Barwala", "Morni", "Panchkula", "Raipur Rani"],
        "Panipat": ["Israna", "Madlauda", "Panipat", "Samalkha"],
        "Rewari": ["Bawal", "Dharuhera", "Jatusana", "Khol", "Kosli", "Nahar", "Rewari"],
        "Rohtak": ["Asthal Bohar", "Kalanaur", "Lakhan Majra", "Maham", "Rohtak", "Sampla"],
        "Sirsa": ["Dabwali", "Ellenabad", "Nathusari Chopta", "Odhan", "Rania", "Sirsa"],
        "Sonipat": ["Ganaur", "Kharkhoda", "Mundlana", "Sonipat"],
        "Yamunanagar": ["Bilaspur", "Chhachhrauli", "Jagadhri", "Mustafabad", "Radaur", "Sadhaura"],
    },
    "Himachal Pradesh": {
        "Bilaspur": ["Bilaspur Sadar", "Ghumarwin", "Jhanda Uta", "Naina Devi", "Namhol", "Swarghat"],
        "Chamba": ["Bharmour", "Chamba", "Churah", "Dalhousie", "Pangi", "Tissa"],
        "Hamirpur": ["Bhoranj", "Hamirpur", "Nadaun", "Sujanpur Tihra"],
        "Kangra": ["Baijnath", "Dehra Gopipur", "Dharamshala", "Fatehpur", "Indora", "Jawali", "Joginder Nagar", "Kangra", "Nagrota Bagwan", "Nurpur", "Palampur", "Rait"],
        "Kinnaur": ["Kalpa", "Nichar", "Pooh"],
        "Kullu": ["Anni", "Banjar", "Kullu", "Nirmand"],
        "Lahaul and Spiti": ["Lahaul", "Spiti"],
        "Mandi": ["Balh", "Chachyot", "Chhuhar Valley", "Darang", "Dharmpur", "Gohar", "Joginder Nagar", "Karsog", "Mandi", "Nihri", "Sadar", "Sarakaghat", "Sarkaghat", "Sundernagar", "Thunag"],
        "Shimla": ["Chopal", "Jubbal", "Kumarsain", "Nankhari", "Rampur", "Rohru", "Shimla", "Theog"],
        "Sirmaur": ["Nahan", "Pachhad", "Paonta Sahib", "Rajgarh", "Sangrah", "Shillai"],
        "Solan": ["Arki", "Kandaghat", "Kasauli", "Nalagarh", "Solan"],
        "Una": ["Amb", "Bangana", "Gagret", "Haroli", "Una"],
    },
    "Jharkhand": {
        "Bokaro": ["Bermo", "Bokaro", "Chas", "Chandankiyari", "Gomia", "Jaridih", "Nawadih", "Petarbar"],
        "Chatra": ["Chatra", "Gidhaur", "Hunterganj", "Itkhori", "Kunda", "Lawalong", "Pathalgada", "Pratappur", "Simaria", "Tandwa"],
        "Deoghar": ["Deoghar", "Madhupur", "Mohanpur", "Palajori", "Sarwan", "Sarodha"],
        "Dhanbad": ["Baghmara", "Baliapur", "Baliyapur", "Dhanbad", "Gobindpur", "Jharia", "Nirsa", "Topchanchi", "Tundi"],
        "Dumka": ["Dumka", "Gopikandar", "Jama", "Jarmundi", "Kathikund", "Masalia", "Ramgarh", "Raneshwar", "Saraiyahat", "Shikaripara"],
        "East Singhbhum": ["Baharagora", "Boram", "Chakulia", "Dhalbhumgarh", "Dhalbhum", "Ghatsila", "Jamshedpur", "Potka"],
        "Garhwa": ["Bhandariya", "Bhawnathpur", "Dhurki", "Garhwa", "Kandi", "Keredari", "Majhiaon", "Meral", "Ramna", "Ranka"],
        "Giridih": ["Bengabad", "Birni", "Dhanwar", "Dumri", "Gandey", "Giridih", "Gawan", "Jamua", "Pirtand", "Surya"],
        "Godda": ["Boarijor", "Godda", "Mahagama", "Pathargama", "Poreyahat", "Sunderpahari"],
        "Gumla": ["Bishunpur", "Basia", "Chainpur", "Dumri", "Ghaghra", "Gumla", "Kamdara", "Palkot", "Raidih", "Simdega"],
        "Hazaribagh": ["Barhi", "Barkagaon", "Bishnugarh", "Chouparan", "Churchu", "Daru", "Hazaribagh", "Ichak", "Katkamsandi", "Mandu", "Padma", "Simaria", "Torpa"],
        "Jamtara": ["Jamtara", "Kundhit", "Mihijam", "Narayanpur", "Nala"],
        "Khunti": ["Arki", "Karra", "Khunti", "Murhu", "Rania", "Torpa"],
        "Koderma": ["Domchanch", "Jainagar", "Koderma", "Markacho", "Satgawan"],
        "Latehar": ["Balumath", "Barwadih", "Chandwa", "Garu", "Latehar", "Mahuadanr", "Manika"],
        "Lohardaga": ["Bhandra", "Kisko", "Kuru", "Lohardaga", "Senha"],
        "Pakur": ["Amrapara", "Hiranpur", "Littipara", "Maheshpur", "Pakur", "Pakuria"],
        "Palamu": ["Chainpur", "Chhatarpur", "Hariharganj", "Hussainabad", "Lesliganj", "Medininagar", "Pandu", "Panki", "Satbarwa", "Vijaynagar"],
        "Ramgarh": ["Dulmi", "Gola", "Mandu", "Patratu", "Ramgarh"],
        "Ranchi": ["Angara", "Bero", "Bundu", "Chanho", "Ormanjhi", "Ratu", "Silli", "Sonahatu", "Tamar"],
        "Sahibganj": ["Barhait", "Borio", "Mandro", "Pathna", "Rajmahal", "Sahibganj", "Taljhari", "Udhwa"],
        "Seraikela Kharsawan": ["Chandil", "Gamharia", "Ichagarh", "Kharsawan", "Kuchai", "Nimdih", "Rajnagar", "Seraikela"],
        "Simdega": ["Bansjor", "Bano", "Bolba", "Jaldega", "Kersai", "Kurdeg", "Pakartanr", "Simdega", "Thethaitangar"],
        "West Singhbhum": ["Chakradharpur", "Chaibasa", "Goilkera", "Gudri", "Jagannathpur", "Khuntpani", "Majhgaon", "Manjhgaon", "Manoharpur", "Noamundi", "Sonua", "Tonto"],
    },
    "Karnataka": {
        "Bagalkot": ["Bagalkot", "Badami", "Bilgi", "Hungund", "Jamkhandi", "Mudhol"],
        "Ballari": ["Ballari", "Hadagali", "Hagaribommanahalli", "Hosapete", "Kampli", "Kudligi", "Sandur", "Siruguppa"],
        "Belagavi": ["Athani", "Bailhongal", "Belagavi", "Chikkodi", "Gokak", "Hukkeri", "Khanapura", "Ramdurg", "Raybag", "Saundatti Yellamma"],
        "Bengaluru Rural": ["Devanahalli", "Doddaballapura", "Hoskote", "Nelamangala"],
        "Bengaluru Urban": ["Anekal", "Bengaluru East", "Bengaluru North", "Bengaluru South", "Yelahanka"],
        "Bidar": ["Aurad", "Basavakalyan", "Bhalki", "Bidar", "Humnabad"],
        "Chamarajanagar": ["Chamarajanagar", "Gundlupet", "Kollegala", "Yelandur"],
        "Chikkaballapura": ["Bagepalli", "Chikkaballapura", "Chintamani", "Gauribidanur", "Gudibanda", "Sidlaghatta"],
        "Chikkamagaluru": ["Chikkamagaluru", "Kadur", "Kalasa", "Koppa", "Mudigere", "Narasimharajapura", "Sringeri", "Tarikere"],
        "Chitradurga": ["Challakere", "Chitradurga", "Hiriyur", "Holalkere", "Hosadurga", "Molakalmuru"],
        "Dakshina Kannada": ["Bantwal", "Belthangady", "Kadaba", "Mangaluru", "Moodabidri", "Puttur", "Sullia", "Ullal"],
        "Davanagere": ["Channagiri", "Davanagere", "Harapanahalli", "Harihara", "Honnali", "Jagaluru"],
        "Dharwad": ["Dharwad", "Hubli", "Kalagatagi", "Kundgol", "Navalgund"],
        "Gadag": ["Gadag", "Mundargi", "Nargund", "Ron", "Shirahatti"],
        "Hassan": ["Alur", "Arakalagudu", "Arkalgud", "Belur", "Hassan", "Holenarasipur", "Sakleshpur"],
        "Haveri": ["Byadagi", "Hangal", "Haveri", "Hirekerur", "Ranebennur", "Savanur", "Shiggaon"],
        "Kalaburagi": ["Afzalpur", "Aland", "Chincholi", "Chittapur", "Gulbarga", "Jewargi", "Sedam", "Shahapur", "Yadgir"],
        "Kodagu": ["Madikeri", "Somvarpet", "Virajpet"],
        "Kolar": ["Bangarpet", "Kolar", "Malur", "Mulbagal", "Srinivasapura"],
        "Koppal": ["Gangavati", "Koppal", "Kushtagi", "Yelburga"],
        "Mandya": ["Krishnarajapete", "Maddur", "Malavalli", "Mandya", "Nagamangala", "Pandavapura", "Shrirangapattana"],
        "Mysuru": ["H D Kote", "Heggadadevankote", "Hunsur", "K R Nagar", "Mysuru", "Nanjangud", "Periyapatna", "T Narasipura"],
        "Raichur": ["Devadurga", "Lingsugur", "Manvi", "Mudgal", "Raichur", "Sindhanur"],
        "Ramanagara": ["Channapatna", "Kanakapura", "Magadi", "Ramanagara"],
        "Shivamogga": ["Bhadravati", "Hosanagara", "Sagara", "Shikaripur", "Shivamogga", "Sorab", "Thirthahalli"],
        "Tumakuru": ["Chiknayakanhalli", "Gubbi", "Koratagere", "Kunigal", "Madhugiri", "Pavagada", "Sira", "Tiptur", "Tumakuru", "Turuvekere"],
        "Udupi": ["Karkala", "Kundapura", "Udupi"],
        "Uttara Kannada": ["Ankola", "Bhatkal", "Haliyal", "Honavar", "Joida", "Karwar", "Kumta", "Mundgod", "Siddapur", "Sirsi", "Supa", "Yellapur"],
        "Vijayapura": ["Basavana Bagevadi", "Bilgi", "Chadachan", "Indi", "Muddebihal", "Sindagi", "Vijayapura"],
        "Yadgir": ["Gurumitkal", "Hunsagi", "Shahapur", "Shorapur", "Yadgir"],
    },
    "Kerala": {
        "Alappuzha": ["Alappuzha", "Ambalappuzha", "Chengannur", "Cherthala", "Karthikappally", "Kuttanad", "Mavelikkara"],
        "Ernakulam": ["Aluva", "Ernakulam", "Kanayannur", "Kodungallur", "Kothamangalam", "Kunnathunad", "Muvattupuzha", "North Paravur", "Paravur"],
        "Idukki": ["Devikulam", "Idukki", "Peerumade", "Thodupuzha", "Udumbanchola"],
        "Kannur": ["Iritty", "Kannur", "Payyannur", "Taliparamba", "Thalassery"],
        "Kasaragod": ["Hosdurg", "Kasaragod", "Manjeshwar", "Vellarikundu"],
        "Kollam": ["Chathannoor", "Kottarakkara", "Kollam", "Kunnathur", "Pathanapuram", "Punalur"],
        "Kottayam": ["Changanacherry", "Erattupetta", "Kanjirappally", "Kottayam", "Meenachil", "Pala", "Vaikom"],
        "Kozhikode": ["Kozhikode", "Koduvally", "Koyilandy", "Mukkam", "Perambra", "Vatakara"],
        "Malappuram": ["Eranad", "Malappuram", "Manjeri", "Nilambur", "Perinthalmanna", "Ponnani", "Tirur", "Tirurrangadi"],
        "Palakkad": ["Alathur", "Attappady", "Chittur", "Mannarkkad", "Palakkad", "Pattambi", "Shoranur"],
        "Pathanamthitta": ["Adoor", "Kozhencherry", "Mallappally", "Pathanamthitta", "Ranni", "Thiruvalla", "Tiruvalla"],
        "Thiruvananthapuram": ["Kattakkada", "Nedumangad", "Neyyattinkara", "Thiruvananthapuram", "Varkala"],
        "Thrissur": ["Chalakudy", "Chavakkad", "Kodungallur", "Mukundapuram", "Talappilly", "Thrissur"],
        "Wayanad": ["Kalpetta", "Mananthavady", "Sulthan Bathery", "Vythiri"],
    },
    "Madhya Pradesh": {
        "Agar Malwa": ["Agar", "Barod", "Nalkheda", "Susner"],
        "Alirajpur": ["Alirajpur", "Bhabhra", "Jobat", "Katthiwada", "Sondwa", "Sorwa", "Udaygarh"],
        "Anuppur": ["Anuppur", "Jaithari", "Kotma", "Pushparajgarh"],
        "Ashoknagar": ["Ashoknagar", "Chanderi", "Isagarh", "Mungaoli"],
        "Balaghat": ["Balaghat", "Baihar", "Birsa", "Katangi", "Kirnapur", "Lanji", "Paraswada", "Waraseoni"],
        "Barwani": ["Barwani", "Niwali", "Pansemal", "Pati", "Rajpur", "Sendhwa", "Thikri"],
        "Betul": ["Amla", "Athner", "Betul", "Bhaisdehi", "Bhainsdehi", "Chicholi", "Ghoradongri", "Multai", "Prabhatpattan", "Sarni", "Shahpur"],
        "Bhind": ["Bhind", "Gohad", "Lahar", "Mehgaon", "Mihona", "Raun"],
        "Bhopal": ["Berasia", "Bhopal", "Huzur", "Phanda"],
        "Burhanpur": ["Burhanpur", "Khaknar", "Nepanagar"],
        "Chhatarpur": ["Bada Malhera", "Bijawar", "Chhatarpur", "Gaurihar", "Harpalpur", "Lavkushnagar", "Nowgong", "Rajnagar"],
        "Chhindwara": ["Amarwara", "Chhindwara", "Harrai", "Jamai", "Mohkhed", "Pandhurna", "Parasia", "Sausar", "Tamia", "Umranala"],
        "Damoh": ["Damoh", "Hatta", "Jabera", "Patera", "Patharia", "Tendukheda"],
        "Datia": ["Bhander", "Datia", "Indergarh", "Seondha"],
        "Dewas": ["Bagli", "Dewas", "Hatpiplya", "Kannod", "Khategaon", "Sonkatch", "Tonkkhurd"],
        "Dhar": ["Badnawar", "Dhar", "Dharampuri", "Gandhwani", "Kukshi", "Manawar", "Sardarpur", "Tirla"],
        "Dindori": ["Amarpur", "Bajag", "Dindori", "Karanjia", "Mehandwani", "Shahpura"],
        "Guna": ["Bamori", "Chachoda", "Guna", "Kumbhraj", "Mungaoli"],
        "Gwalior": ["Bhitarwar", "Dabra", "Gwalior", "Morar"],
        "Harda": ["Harda", "Timarni"],
        "Hoshangabad": ["Babai", "Hoshangabad", "Itarsi", "Kesla", "Pipariya", "Seoni-Malwa", "Sohagpur"],
        "Indore": ["Depalpur", "Hatod", "Indore", "Mhow", "Sanwer"],
        "Jabalpur": ["Jabalpur", "Kundam", "Majholi", "Patan", "Seoni", "Shahpura", "Sihora"],
        "Jhabua": ["Jobat", "Jhabua", "Meghnagar", "Petlawad", "Rama", "Ranapur", "Thandla"],
        "Katni": ["Badwara", "Bahoriband", "Dhimarkheda", "Katni", "Mudwara", "Riti", "Vijayraghavgarh"],
        "Khandwa": ["Harsud", "Khalwa", "Khandwa", "Khalwa", "Pandhana", "Punasa"],
        "Khargone": ["Barwaha", "Bhikangaon", "Gogawan", "Khargone", "Maheshwar", "Sanawad", "Segaon", "Ziranyia"],
        "Mandla": ["Bichhia", "Ghugri", "Mandla", "Mawai", "Narayanganj", "Niwas"],
        "Mandsaur": ["Daloda", "Garoth", "Malhargarh", "Mandsaur", "Sitamau", "Suwasra"],
        "Morena": ["Ambah", "Joura", "Kailaras", "Morena", "Porsa", "Sabalgarh"],
        "Narsimhapur": ["Babai", "Gadarwara", "Gotegaon", "Kareli", "Narsimhapur", "Tendukheda"],
        "Neemuch": ["Jawad", "Manasa", "Neemuch"],
        "Niwari": ["Niwari", "Orchha", "Prithvipur"],
        "Panna": ["Ajaygarh", "Gunnaur", "Panna", "Pawai", "Shahnagar"],
        "Raisen": ["Bareli", "Begumganj", "Gairatganj", "Obaidullahganj", "Raisen", "Sanchi", "Silwani", "Udaipura"],
        "Rajgarh": ["Biaora", "Jirapur", "Khilchipur", "Kurawar", "Narsingarh", "Rajgarh", "Sarangpur"],
        "Ratlam": ["Alot", "Bajna", "Jaora", "Ratlam", "Sailana"],
        "Rewa": ["Gangev", "Gurh", "Hanumana", "Mangawan", "Mauganj", "Naigarhi", "Rewa", "Sirmaur", "Tyonthar"],
        "Sagar": ["Bina", "Deori", "Khurai", "Rahatgarh", "Sagar", "Rehli"],
        "Satna": ["Amarpatan", "Birsinghpur", "Chitrakoot", "Maihar", "Nagod", "Rampur Baghelan", "Satna", "Uchehara"],
        "Sehore": ["Ashta", "Budhni", "Ichhawar", "Nasrullaganj", "Rehti", "Sehore"],
        "Seoni": ["Barghat", "Chhapara", "Dhanora", "Ghansore", "Keolari", "Kurai", "Lakhnadon", "Seoni"],
        "Shahdol": ["Beohari", "Burhar", "Jaisinghnagar", "Shahdol", "Sohagpur"],
        "Shajapur": ["Agar", "Kalapipal", "Moman Badodiya", "Shajapur", "Shujalpur", "Sunner"],
        "Sheopur": ["Karhal", "Sheopur", "Vijaypur"],
        "Shivpuri": ["Badarwas", "Karera", "Khaniyadhana", "Kolaras", "Pichhore", "Pohari", "Shivpuri"],
        "Sidhi": ["Churhat", "Kusmi", "Rampur Naikin", "Sidhi", "Singrauli"],
        "Singrauli": ["Chitrangi", "Devsar", "Singrauli", "Waidhan"],
        "Tikamgarh": ["Baldeogarh", "Jatara", "Khargapur", "Niwari", "Palera", "Prithvipur", "Tikamgarh"],
        "Ujjain": ["Badnagar", "Ghattiya", "Khachrod", "Mahidpur", "Nagda", "Tarana", "Ujjain"],
        "Umaria": ["Bandhogarh", "Chandiya", "Manpur", "Umaria"],
        "Vidisha": ["Basoda", "Gyraspur", "Kurwai", "Lateri", "Nateran", "Sironj", "Vidisha"],
    },
    "Maharashtra": {
        "Ahmednagar": ["Ahmednagar", "Akole", "Jamkhed", "Karjat", "Kopargaon", "Nagar", "Nevasa", "Parner", "Pathardi", "Rahata", "Rahuri", "Sangamner", "Shevgaon", "Shrigonda", "Shrirampur"],
        "Akola": ["Akola", "Akot", "Balapur", "Barshitakli", "Murtizapur", "Patur", "Telhara"],
        "Amravati": ["Achalpur", "Amravati", "Anjangaon Surji", "Chandur Bazar", "Chandur Railway", "Chikhaldara", "Daryapur", "Dhamangaon Railway", "Morshi", "Nandgaon-Khandeshwar", "Teosa", "Warud"],
        "Aurangabad": ["Aurangabad", "Gangapur", "Kannad", "Khuldabad", "Paithan", "Phulambri", "Sillod", "Soegaon", "Vaijapur"],
        "Beed": ["Ambajogai", "Ashti", "Beed", "Dharur", "Georai", "Kaij", "Majalgaon", "Parali", "Patoda", "Shirur Kasar"],
        "Bhandara": ["Bhandara", "Lakhandur", "Lakhani", "Mohadi", "Pauni", "Sakoli", "Tumsar"],
        "Buldhana": ["Buldhana", "Chikhli", "Deulgaon Raja", "Jalgaon Jamod", "Khamgaon", "Lonar", "Malkapur", "Mehkar", "Motala", "Nandura", "Sangrampur", "Shegaon", "Sindkhed Raja"],
        "Chandrapur": ["Ballarpur", "Bhadravati", "Brahmapuri", "Chandrapur", "Chimur", "Gondpimpri", "Jiwati", "Korpana", "Mul", "Nagbhid", "Pombhurna", "Rajura", "Sawali", "Sindewahi", "Warora"],
        "Dhule": ["Dhule", "Sakri", "Shirpur", "Sindkheda"],
        "Gadchiroli": ["Aheri", "Armori", "Bhamragad", "Chamorshi", "Dhanora", "Desaiganj", "Etapalli", "Gadchiroli", "Korchi", "Kurkheda", "Mulchera", "Sironcha"],
        "Gondia": ["Amgaon", "Arjuni Morgaon", "Deori", "Gondiya", "Goregaon", "Sadak Arjuni", "Salekasa", "Tirora"],
        "Hingoli": ["Aundha Nagnath", "Basmat", "Hingoli", "Kalamnuri", "Sengaon"],
        "Jalgaon": ["Amalner", "Bhadgaon", "Bhusawal", "Bodwad", "Chalisgaon", "Chopda", "Erandol", "Jalgaon", "Jamner", "Muktainagar", "Pachora", "Parola", "Raver", "Yawal"],
        "Jalna": ["Ambad", "Badnapur", "Bhokardan", "Ghansawangi", "Jafrabad", "Jalna", "Mantha", "Partur"],
        "Kolhapur": ["Ajra", "Bavda", "Bhudargad", "Chandgad", "Gadhinglaj", "Hatkanangle", "Kagal", "Karvir", "Panhala", "Radhanagari", "Shahuwadi", "Shirol"],
        "Latur": ["Ahmadpur", "Ausa", "Chakur", "Deoni", "Jalkot", "Latur", "Nilanga", "Renapur", "Shirur Anantpal", "Udgir"],
        "Mumbai City": ["Colaba", "Kurla", "Mumbai City"],
        "Mumbai Suburban": ["Andheri", "Borivali", "Kurla"],
        "Nagpur": ["Bhiwapur", "Hingna", "Kamptee", "Katol", "Kuhi", "Mauda", "Nagpur Rural", "Nagpur Urban", "Narkhed", "Parseoni", "Ramtek", "Savner", "Umred"],
        "Nanded": ["Ardhapur", "Biloli", "Bhokar", "Deglur", "Dharmabad", "Hadgaon", "Himayatnagar", "Kandhar", "Kinwat", "Loha", "Mahur", "Mudkhed", "Mukhed", "Nanded", "Naigaon", "Umri"],
        "Nandurbar": ["Akkalkuwa", "Akrani", "Nandurbar", "Nawapur", "Shahada", "Taloda"],
        "Nashik": ["Baglan", "Chandwad", "Deola", "Dindori", "Igatpuri", "Kalwan", "Malegaon", "Nandgaon", "Nashik", "Niphad", "Peth", "Sinnar", "Surgana", "Trimbakeshwar", "Yeola"],
        "Osmanabad": ["Kalamb", "Lohara", "Osmanabad", "Paranda", "Tuljapur", "Umarga", "Washi"],
        "Palghar": ["Dahanu", "Jawhar", "Mokhada", "Palghar", "Talasari", "Vasai", "Vikramgad", "Wada"],
        "Parbhani": ["Gangakhed", "Jintur", "Manwath", "Palam", "Parbhani", "Pathri", "Purna", "Sailu", "Selu", "Sonpeth"],
        "Pune": ["Ambegaon", "Baramati", "Bhor", "Daund", "Haveli", "Indapur", "Junnar", "Khed", "Mawal", "Mulshi", "Purandar", "Pune City", "Shirur", "Velhe"],
        "Raigad": ["Alibag", "Karjat", "Khalapur", "Mahad", "Mangaon", "Mhasla", "Murud", "Panvel", "Pen", "Poladpur", "Roha", "Shrivardhan", "Sudhagad", "Tala", "Uran"],
        "Ratnagiri": ["Chiplun", "Dapoli", "Guhagar", "Khed", "Lanja", "Mandangad", "Rajapur", "Ratnagiri", "Sangameshwar"],
        "Sangli": ["Atpadi", "Jat", "Kadegaon", "Kavathemahankal", "Khanapur", "Miraj", "Palus", "Shirala", "Tasgaon", "Valva", "Walwa"],
        "Satara": ["Jaoli", "Khandala", "Khatav", "Koregaon", "Mahabaleshwar", "Man", "Patan", "Phaltan", "Satara", "Wai"],
        "Sindhudurg": ["Devgad", "Dodamarg", "Kankavli", "Kudal", "Malvan", "Sawantwadi", "Vaibhavwadi", "Vengurla"],
        "Solapur": ["Akkalkot", "Barshi", "Karmala", "Madha", "Malshiras", "Mangalvedha", "Mohol", "Pandharpur", "Sangola", "Solapur North", "Solapur South"],
        "Thane": ["Ambarnath", "Bhiwandi", "Kalyan", "Murbad", "Shahapur", "Thane", "Ulhasnagar"],
        "Wardha": ["Arvi", "Ashti", "Deoli", "Hinganghat", "Karanja", "Seloo", "Samudrapur", "Wardha"],
        "Washim": ["Karanja", "Malegaon", "Mangrulpir", "Manora", "Risod", "Washim"],
        "Yavatmal": ["Arni", "Babulgaon", "Darwha", "Digras", "Ghatanji", "Kalamb", "Kelapur", "Mahagaon", "Maregaon", "Ner", "Pusad", "Ralegaon", "Umarkhed", "Wani", "Yavatmal", "Zari Jamni"],
    },
    "Manipur": {
        "Bishnupur": ["Bishnupur", "Nambol", "Ningthoukhong", "Moirang"],
        "Chandel": ["Chakpikarong", "Chandel", "Henglep", "Machi", "Tengnoupal"],
        "Churachandpur": ["Churachandpur", "Henglep", "Thanlon", "Tipaimukh"],
        "Imphal East": ["Heingang", "Imphal East", "Jiribam", "Lamlai", "Porompat"],
        "Imphal West": ["Imphal West", "Lamphel", "Patsoi", "Sekmai", "Wangoi"],
        "Jiribam": ["Jiribam"],
        "Kakching": ["Kakching", "Sugnu", "Waikhong"],
        "Kamjong": ["Kamjong", "Nungba"],
        "Kangpokpi": ["Kangpokpi", "Saitu", "Saikul"],
        "Noney": ["Noney", "Tousem"],
        "Pherzawl": ["Churachandpur", "Pherzawl"],
        "Senapati": ["Mao", "Paomata", "Purul", "Senapati"],
        "Tamenglong": ["Nungba", "Tamenglong", "Tousem"],
        "Tengnoupal": ["Moreh", "Tengnoupal"],
        "Thoubal": ["Kakching", "Lilong", "Thoubal", "Wangjing", "Yairipok"],
        "Ukhrul": ["Chingai", "Kambiron", "Phungyar", "Ukhrul"],
    },
    "Meghalaya": {
        "East Garo Hills": ["Bajengdoba", "Resubelpara", "Samanda", "Williams Nagar"],
        "East Jaintia Hills": ["Amlarem", "Khliehriat", "Saipung"],
        "East Khasi Hills": ["Mairang", "Mylliem", "Pynursla", "Shella-Bholaganj", "Shillong", "Sohryngkham"],
        "North Garo Hills": ["Resubelpara"],
        "Ri Bhoi": ["Jirang", "Nongpoh", "Umsning"],
        "South Garo Hills": ["Baghmara", "Rongram"],
        "South West Garo Hills": ["Ampati", "Mahendraganj"],
        "South West Khasi Hills": ["Mawkyrwat"],
        "West Garo Hills": ["Dalu", "Phulbari", "Selsella", "Tura"],
        "West Jaintia Hills": ["Jowai", "Laskein", "Thadlaskein"],
        "West Khasi Hills": ["Nongstoin", "Ranikor"],
    },
    "Mizoram": {
        "Aizawl": ["Aizawl", "Darlawn", "Phullen", "Tlangnuam"],
        "Champhai": ["Champhai", "Khawzawl", "Ngopa"],
        "Hnahthial": ["Hnahthial"],
        "Khawzawl": ["Khawzawl"],
        "Kolasib": ["Kolasib", "Thingdawl"],
        "Lawngtlai": ["Lawngtlai", "Sangau"],
        "Lunglei": ["Lunglei", "Lungsen", "Tlabung"],
        "Mamit": ["Mamit", "West Phaileng"],
        "Saiha": ["Saiha"],
        "Saitual": ["Saitual"],
        "Serchhip": ["Serchhip", "Thenzawl"],
    },
    "Nagaland": {
        "Dimapur": ["Dimapur", "Medziphema"],
        "Kiphire": ["Kiphire", "Seyochung"],
        "Kohima": ["Kohima", "Viswema"],
        "Longleng": ["Longleng"],
        "Mokokchung": ["Mokokchung", "Tuli"],
        "Mon": ["Aboi", "Mon", "Tizit"],
        "Noklak": ["Noklak"],
        "Peren": ["Peren", "Jalukie"],
        "Phek": ["Chozuba", "Meluri", "Phek"],
        "Tuensang": ["Noksen", "Shamator", "Tobu", "Tuensang"],
        "Wokha": ["Bhandari", "Wokha"],
        "Zunheboto": ["Aghunato", "Satakha", "Zunheboto"],
    },
    "Odisha": {
        "Angul": ["Angul", "Athamallik", "Banarpal", "Chhendipada", "Kaniha", "Pallahara", "Talcher"],
        "Balangir": ["Agalpur", "Bangomunda", "Belpara", "Deogaon", "Gudvella", "Kantabanji", "Muribahal", "Patnagarh", "Puintala", "Saintala", "Titilagarh"],
        "Balasore": ["Balasore", "Baliapal", "Bahanaga", "Bhograi", "Jaleswar", "Nilagiri", "Remuna", "Simulia", "Soro"],
        "Bargarh": ["Attabira", "Bargarh", "Bhatli", "Bijepur", "Boudh", "Gaisilet", "Jharbandh", "Padampur", "Paikmal", "Rajborasambar", "Sohella"],
        "Bhadrak": ["Basudevpur", "Bhadrak", "Bonth", "Chandbali", "Dhamnagar", "Tihidi"],
        "Boudh": ["Boudh", "Kantamal"],
        "Cuttack": ["Athagad", "Athagarh", "Banki", "Baramba", "Cuttack", "Dampara", "Kanpur Natham", "Niali", "Salepur", "Tangi"],
        "Deogarh": ["Barkote", "Deogarh", "Reamal"],
        "Dhenkanal": ["Bhuban", "Dhenkanal", "Gondia", "Hindol", "Kamakhyanagar", "Odapada", "Parjang"],
        "Gajapati": ["Gumma", "Kashinagar", "Mohana", "R Udayagiri"],
        "Ganjam": ["Aska", "Bhanjanagar", "Berhampur", "Buguda", "Chhatrapur", "Chikiti", "Digapahandi", "Hinjilicut", "Jagannathprasad", "Khallikote", "Kodala", "Kukudakhandi", "Patrapur", "Polasara", "Purusottampur", "Sanakhemundi", "Sheragada", "Sorada"],
        "Jagatsinghpur": ["Balikuda", "Biridi", "Erasama", "Jagatsinghpur", "Kujang", "Raghunathpur", "Tirtol"],
        "Jajpur": ["Barchana", "Badachana", "Binjharpur", "Danagadi", "Dharmasala", "Jajpur", "Korei", "Rasulpur", "Sukinda"],
        "Jharsuguda": ["Jharsuguda", "Kirmira", "Kolabira", "Lakhanpur"],
        "Kalahandi": ["Bhawanipatna", "Dharmagarh", "Golamunda", "Junagarh", "Koksara", "Lanjigarh", "M Rampur", "Narla", "Thuamul Rampur"],
        "Kandhamal": ["Baliguda", "G Udayagiri", "Khajuripada", "Phulbani", "Tikabali"],
        "Kendrapara": ["Aul", "Derabish", "Kendrapara", "Mahakalapara", "Marshaghai", "Pattamundai", "Rajnagar"],
        "Kendujhar": ["Champua", "Ghasipura", "Harichandanpur", "Jhumpura", "Kendujhar", "Sadar", "Telkoi", "Turumunga"],
        "Khordha": ["Balianta", "Balugaon", "Banapur", "Bhubaneswar", "Bolagarh", "Chilika", "Jatni", "Khordha", "Tangi-Choudwar"],
        "Koraput": ["Boipariguda", "Dasmantpur", "Jeypore", "Koraput", "Kotpad", "Kundra", "Laxmipur", "Nandapur", "Narayanpatna", "Pottangi", "Similiguda"],
        "Malkangiri": ["Kalimela", "Khairiput", "Khairput", "Malkangiri", "Mathili", "Podia"],
        "Mayurbhanj": ["Badasahi", "Bahalda", "Bangriposi", "Baripada", "Bisoi", "Jashipur", "Karanjia", "Kaptipada", "Kusumi", "Moroda", "Palbani", "Rairangpur", "Saraskana", "Suliapada"],
        "Nabarangpur": ["Dabugam", "Jharigaon", "Kosagumuda", "Nabarangpur", "Nandahandi", "Papadahandi", "Raighar", "Tentulikhunti", "Umarkote"],
        "Nayagarh": ["Bhapur", "Daspalla", "Khandapara", "Nayagarh", "Nuagaon", "Odagaon", "Ranpur"],
        "Nuapada": ["Boden", "Khariar", "Komna", "Nuapada", "Sinapali"],
        "Puri": ["Astaranga", "Brahmagiri", "Delang", "Kakatpur", "Kanas", "Konark", "Nimapara", "Pipili", "Puri", "Satyabadi"],
        "Rayagada": ["Bissamcuttack", "Gunupur", "Kashipur", "Kolnara", "Padmapur", "Rayagada"],
        "Sambalpur": ["Bamra", "Jamankira", "Jujomura", "Kuchinda", "Maneswar", "Naktideul", "Rairakhol", "Sambalpur"],
        "Sonepur": ["Birmaharajpur", "Dunguripali", "Sonepur", "Tarava", "Ulunda"],
        "Sundargarh": ["Bonai", "Hemgir", "Kuanrmunda", "Lahunipara", "Lephripada", "Rajgangpur", "Sundargarh", "Tangarpali"],
    },
    "Punjab": {
        "Amritsar": ["Ajnala", "Amritsar North", "Amritsar South", "Baba Bakala", "Majitha"],
        "Barnala": ["Barnala", "Dhanaula", "Mehal Kalan"],
        "Bathinda": ["Bathinda", "Maur", "Nathana", "Phul", "Rampura Phul", "Sangat", "Talwandi Sabo"],
        "Faridkot": ["Faridkot", "Jaitu", "Kotkapura"],
        "Fatehgarh Sahib": ["Amloh", "Bassi Pathana", "Fatehgarh Sahib", "Khamanon", "Morinda"],
        "Fazilka": ["Abohar", "Fazilka", "Jalalabad"],
        "Ferozepur": ["Ferozepur", "Fazilka", "Guru Har Sahai", "Jalalabad", "Zira"],
        "Gurdaspur": ["Batala", "Dina Nagar", "Dera Baba Nanak", "Dhariwal", "Gurdaspur", "Kalanaur", "Pathankot", "Qadian"],
        "Hoshiarpur": ["Dasuya", "Garhshankar", "Hoshiarpur", "Mukerian", "Tanda"],
        "Jalandhar": ["Jalandhar East", "Jalandhar West", "Nakodar", "Phillaur", "Shahkot"],
        "Kapurthala": ["Bhulath", "Dhilwan", "Kapurthala", "Phagwara", "Sultanpur Lodhi"],
        "Ludhiana": ["Dehlon", "Jagraon", "Khanna", "Ludhiana East", "Ludhiana West", "Payal", "Raikot", "Samrala"],
        "Malerkotla": ["Ahmedgarh", "Amargarh", "Malerkotla"],
        "Mansa": ["Budhlada", "Mansa", "Sardulgarh"],
        "Moga": ["Baghapurana", "Dharamkot", "Moga", "Nihal Singh Wala"],
        "Mohali": ["Derabassi", "Dera Bassi", "Kharar", "Mohali"],
        "Muktsar": ["Gidderbaha", "Lambi", "Malout", "Muktsar"],
        "Nawanshahr": ["Balachaur", "Banga", "Nawanshahr"],
        "Pathankot": ["Dharkalan", "Pathankot", "Sujanpur"],
        "Patiala": ["Nabha", "Patiala", "Rajpura", "Samana", "Sanaur"],
        "Rupnagar": ["Anandpur Sahib", "Chamkaur Sahib", "Nangal", "Nurpur Bedi", "Rupnagar"],
        "Sangrur": ["Ahmedgarh", "Bhawanigarh", "Dhuri", "Dirba", "Lehra", "Malerkotla", "Moonak", "Sangrur", "Sherpur", "Sunam"],
        "Shahid Bhagat Singh Nagar": ["Balachaur", "Banga", "Nawanshahr"],
        "Sri Muktsar Sahib": ["Gidderbaha", "Lambi", "Malout", "Muktsar"],
        "Tarn Taran": ["Khem Karan", "Patti", "Tarn Taran"],
    },
    "Rajasthan": {
        "Ajmer": ["Ajmer", "Beawar", "Bhinai", "Kekri", "Kishangarh", "Masuda", "Nasirabad", "Pushkar", "Roopangarh", "Sarwar", "Shrinagar", "Srinagar", "Tatgarh"],
        "Alwar": ["Alwar", "Bahror", "Bansur", "Kathumar", "Kishangarh Bas", "Kotkasim", "Lakshmangarh", "Laxmangarh", "Mandawar", "Mundawar", "Neemrana", "Rajgarh", "Ramgarh", "Tapukara", "Thanagazi", "Tijara"],
        "Banswara": ["Bagidora", "Banswara", "Chhoti Sarwan", "Ghatol", "Garhi", "Kushalgarh", "Talwara"],
        "Baran": ["Anta", "Atru", "Baran", "Chhipabarod", "Chhabra", "Kelwara", "Kishanganj", "Mangrol", "Sheosinghpur"],
        "Barmer": ["Baitu", "Barmer", "Baytu", "Chohtan", "Dhorimanna", "Gadra Road", "Gudhamalani", "Pachpadra", "Ramsar", "Sheo", "Siwana"],
        "Bharatpur": ["Bayana", "Bharatpur", "Deeg", "Kaman", "Kumher", "Nadbai", "Nagar", "Pahari", "Rupbas", "Sewar", "Sikandra", "Weir"],
        "Bhilwara": ["Asind", "Banera", "Bhilwara", "Gangapur", "Hamirgarh", "Hurda", "Jahazpur", "Kotri", "Mandalgarh", "Phuliana", "Raipur", "Sahara", "Shahpura"],
        "Bikaner": ["Bikaner", "Colayat", "Dungargarh", "Khajuwala", "Lunkaransar", "Nokha", "Poogal"],
        "Bundi": ["Bundi", "Hindoli", "Indergarh", "Keshoraipatan", "Nainwa", "Talera"],
        "Chittorgarh": ["Begun", "Bhadesar", "Bhupal Sagar", "Chittorgarh", "Dungla", "Gangrar", "Kapasan", "Nimbahera", "Rashmi", "Rawatbhata"],
        "Churu": ["Churu", "Rajgarh", "Ratangarh", "Sardarshahar", "Sujangarh", "Taranagar"],
        "Dausa": ["Bandikui", "Dausa", "Lalsot", "Mahuwa", "Nangal Rajawatan", "Ramgarh Pachwara", "Sikrai"],
        "Dholpur": ["Badi", "Baseri", "Dholpur", "Rajakheda", "Sarmathura"],
        "Dungarpur": ["Aspur", "Bichhiwara", "Chikhali", "Dungarpur", "Galiyakot", "Sabla", "Sagwara", "Simalwara"],
        "Hanumangarh": ["Bhadra", "Hanumangarh", "Nohar", "Pilibanga", "Rawatsar", "Sangaria", "Tibi"],
        "Jaipur": ["Amber", "Amer", "Bassi", "Chaksu", "Chomu", "Dudu", "Jamwa Ramgarh", "Jaipur", "Jhotwara", "Kotputli", "Kotkhawda", "Phagi", "Sambhar", "Sanganer", "Shahpura", "Viratnagar"],
        "Jaisalmer": ["Fatehgarh", "Jaisalmer", "Pokaran", "Sam", "Sankra"],
        "Jalore": ["Ahore", "Bhinmal", "Jalore", "Jaswantpura", "Raniwara", "Sanchore", "Sayla"],
        "Jhalawar": ["Aklera", "Bakani", "Bhawani Mandi", "Dag", "Gangdhar", "Jhalawar", "Khanpur", "Manohar Thana", "Pirawa", "Sunel"],
        "Jhunjhunu": ["Buhana", "Chirawa", "Jhunjhunu", "Khetri", "Mandawa", "Nawalgarh", "Pilani", "Surajgarh", "Udaipurwati"],
        "Jodhpur": ["Bap", "Baori", "Bilara", "Bhopalgarh", "Jodhpur", "Luni", "Mandor", "Osian", "Phalodi", "Pipar", "Senasingla", "Shergarh", "Sherpur"],
        "Karauli": ["Hindaun", "Karauli", "Mandrayal", "Masalpur", "Nadoti", "Sapotra", "Shri Mahaveerji", "Suroth", "Todabhim"],
        "Kota": ["Itawa", "Kota", "Kanwas", "Ladpura", "Pipalda", "Ramganj Mandi", "Sangar", "Sultanpur"],
        "Nagaur": ["Degana", "Didwana", "Jayal", "Khinvsar", "Ladnun", "Makrana", "Merta", "Merta City", "Mundwa", "Nagaur", "Nawa", "Parbatsar", "Riyan Badi"],
        "Pali": ["Bali", "Desuri", "Jaitaran", "Kharchi", "Marwar Junction", "Pali", "Pindwara", "Raipur", "Rohat", "Sojat", "Sumerpur"],
        "Pratapgarh": ["Arnod", "Chhoti Sadri", "Dhariawad", "Partapgarh", "Peepalkhoont"],
        "Rajsamand": ["Amet", "Bhim", "Deogarh", "Kumbhalgarh", "Nathdwara", "Rajsamand", "Railmagra", "Relmagra"],
        "Sawai Madhopur": ["Bonli", "Gangapur City", "Khandar", "Malarna Dungar", "Sawai Madhopur", "Wazirpur"],
        "Sikar": ["Danta Ramgarh", "Dhod", "Fatehpur", "Khandela", "Laxmangarh", "Neem Ka Thana", "Piprali", "Ramgarh", "Shrimadhopur", "Sikar", "Sri Madhopur"],
        "Sirohi": ["Abu Road", "Pindwara", "Reodar", "Sheoganj", "Sirohi"],
        "Sri Ganganagar": ["Anupgarh", "Gharsana", "Karanpur", "Padampur", "Raisinghnagar", "Sadulshahar", "Sri Ganganagar", "Suratgarh", "Tibbi", "Vijaynagar"],
        "Tonk": ["Deoli", "Malpura", "Newai", "Niwai", "Peeplu", "Tonk", "Uniara"],
        "Udaipur": ["Badgaon", "Bhinder", "Gogunda", "Girwa", "Jhadol", "Kherwara", "Kotra", "Lasadia", "Mavli", "Salumbar", "Sarada", "Udaipur", "Vallabhnagar"],
    },
    "Sikkim": {
        "East Sikkim": ["Gangtok", "Pakyong", "Ranka", "Rongli"],
        "North Sikkim": ["Chungthang", "Mangan"],
        "South Sikkim": ["Jorethang", "Namchi", "Ravangla", "Temi"],
        "West Sikkim": ["Dentam", "Gyalshing", "Soreng"],
    },
    "Tamil Nadu": {
        "Ariyalur": ["Ariyalur", "Jayankondam", "Sendurai", "Udayarpalayam"],
        "Chengalpattu": ["Chengalpattu", "Cheyyur", "Maduranthakam", "Tiruporur"],
        "Chennai": ["Ambattur", "Ayanavaram", "Chennai", "Egmore", "Fort", "Mambalam", "Mylapore", "Sholinganallur", "Tambaram", "Tondiarpet"],
        "Coimbatore": ["Annur", "Coimbatore North", "Coimbatore South", "Kinathukadavu", "Madukkarai", "Mettupalayam", "Palladam", "Perur", "Pollachi", "Sulur", "Valparai"],
        "Cuddalore": ["Bhuvanagiri", "Chidambaram", "Cuddalore", "Kattumannarkoil", "Kurinjipadi", "Panruti", "Parangipettai", "Srimushnam", "Tittagudi", "Vriddhachalam"],
        "Dharmapuri": ["Dharmapuri", "Harur", "Nammiyambattu", "Palacode", "Pennagaram"],
        "Dindigul": ["Attur", "Dindigul", "Kodaikanal", "Nilakottai", "Oddanchatram", "Palani", "Reddiyarchatram", "Vedasandur"],
        "Erode": ["Bhavani", "Erode", "Gobichettipalayam", "Kodumudi", "Modakkurichi", "Nambiyur", "Perundurai", "Sathyamangalam"],
        "Kallakurichi": ["Chinnasalem", "Kallakurichi", "Sankarapuram", "Ulundurpet"],
        "Kanchipuram": ["Kanchipuram", "Sriperumbudur", "Uthiramerur", "Walajabad"],
        "Kanyakumari": ["Agastheeswaram", "Kalkulam", "Killiyoor", "Thovalai", "Vilavancode"],
        "Karur": ["Aravakurichi", "Karur", "Krishnarayapuram", "Kulithalai", "Manmangalam"],
        "Krishnagiri": ["Bargur", "Denkanikottai", "Hosur", "Krishnagiri", "Pochampalli", "Uthangarai", "Veppanahalli"],
        "Madurai": ["Madurai North", "Madurai South", "Melur", "Peraiyur", "Thiruppanandal", "Usilampatti", "Vadipatti"],
        "Mayiladuthurai": ["Kuthalam", "Mayiladuthurai", "Sirkazhi", "Sirkali"],
        "Nagapattinam": ["Kilvelur", "Mayiladuthurai", "Nagapattinam", "Tharangambadi", "Vedaranyam"],
        "Namakkal": ["Kolli Hills", "Kumarapalayam", "Mohanur", "Namakkal", "Paramathi Velur", "Rasipuram", "Sendamangalam"],
        "Nilgiris": ["Gudalur", "Kotagiri", "Ooty", "Pandalur"],
        "Perambalur": ["Arumbavur", "Kunnam", "Perambalur", "Veppanthattai"],
        "Pudukkottai": ["Aranthangi", "Avudayarkoil", "Gandarvakottai", "Iluppur", "Karambakudi", "Kulathur", "Manamelkudi", "Ponnamaravathi", "Pudukkottai", "Thirumayam", "Viralimalai"],
        "Ramanathapuram": ["Kadaladi", "Kamuthi", "Mudukulathur", "Paramakudi", "Rajasingamangalam", "Ramanathapuram", "Rameswaram", "Thiruvadanai"],
        "Ranipet": ["Arcot", "Arakkonam", "Nemili", "Sholinghur", "Walajah"],
        "Salem": ["Attur", "Edappadi", "Gangavalli", "Kadayampatti", "Mettur", "Omalur", "Salem", "Sankari", "Vazhapadi", "Yercaud"],
        "Sivaganga": ["Devakottai", "Ilayangudi", "Kalayarkoil", "Manamadurai", "Sivaganga", "Tirupuvanam"],
        "Tenkasi": ["Alangulam", "Kadayanallur", "Sankarankovil", "Shencottah", "Sivagiri", "Tenkasi"],
        "Thanjavur": ["Budalur", "Kumbakonam", "Orathanadu", "Papanasam", "Pattukkottai", "Peravurani", "Thanjavur", "Thiruvidaimarudur"],
        "Theni": ["Andipatti", "Bodinayakkanur", "Periyakulam", "Theni Allinagaram", "Uthamapalayam"],
        "Thoothukudi": ["Ettayapuram", "Kovilpatti", "Ottapidaram", "Srivaikundam", "Tiruchendur", "Thoothukudi", "Vilathikulam"],
        "Tiruchirappalli": ["Lalgudi", "Manachanallur", "Manapparai", "Marungapuri", "Musiri", "Srirangam", "Thottiyam", "Tiruverambur", "Tiruchirappalli", "Uppiliyapuram"],
        "Tirunelveli": ["Ambasamudram", "Cheranmahadevi", "Manur", "Nanguneri", "Palayamkottai", "Radhapuram", "Tirunelveli"],
        "Tirupathur": ["Ambur", "Natrampalli", "Tirupathur", "Vaniyambadi"],
        "Tiruppur": ["Avinashi", "Dharapuram", "Gudimangalam", "Kangeyam", "Madathukulam", "Palladam", "Tiruppur", "Udumalaipettai", "Uthukuli"],
        "Tiruvallur": ["Ponneri", "Poonamallee", "Thiruvallur", "Tiruttani", "Utukottai"],
        "Tiruvannamalai": ["Arani", "Chetpet", "Chengam", "Jawadhu Hills", "Kalasapakkam", "Polur", "Tiruvannamalai", "Vandavasi", "Vembakkam"],
        "Tiruvarur": ["Kodavasal", "Mannargudi", "Nannilam", "Needamangalam", "Papanasam", "Tiruvarur", "Valangaiman"],
        "Vellore": ["Anaicut", "Gudiyatham", "Katpadi", "Pernambut", "Vellore", "Walajah"],
        "Villupuram": ["Gingee", "Kallakurichi", "Marakanam", "Mugaiyur", "Rishivandiyam", "Tindivanam", "Ulundurpet", "Vanur", "Villupuram", "Vikravandi"],
        "Virudhunagar": ["Aruppukkottai", "Kariapatti", "Rajapalayam", "Sattur", "Sivakasi", "Srivilliputhur", "Tiruchuli", "Virudhunagar", "Watrap"],
    },
    "Telangana": {
        "Adilabad": ["Adilabad", "Bela", "Boath", "Gudihatnoor", "Ichoda", "Jainath", "Talamadugu", "Utnoor"],
        "Bhadradri Kothagudem": ["Aswaraopeta", "Bhadrachalam", "Burgampahad", "Cherla", "Dammapeta", "Julurpad", "Kothagudem", "Manuguru", "Palwancha", "Pinapaka", "Yellandu"],
        "Hyderabad": ["Amberpet", "Charminar", "Khairatabad", "Musheerabad", "Nampally", "Secunderabad", "Shaikpet"],
        "Jagtial": ["Dharmapuri", "Gollapalli", "Jagtial", "Korutla", "Metpally", "Pegadapalli", "Raikal"],
        "Jangaon": ["Bachannapeta", "Devaruppula", "Ghanpur", "Jangaon", "Kodakandla", "Palakurthi", "Raghunathpally", "Zaffergadh"],
        "Jayashankar Bhupalpally": ["Bhupalpally", "Chityal", "Govindaraopet", "Kataram", "Mahadevpur", "Manthani", "Palimela", "Regonda", "Tekumatla"],
        "Jogulamba Gadwal": ["Alampur", "Gadwal", "Gattu", "Ieeja", "Maldakal"],
        "Kamareddy": ["Banswada", "Bichkunda", "Domakonda", "Kamareddy", "Lingampet", "Machareddy", "Madnoor", "Nizamsagar", "Pitlam", "Yellareddy"],
        "Karimnagar": ["Choppadandi", "Huzurabad", "Karimnagar", "Kothapalli", "Manakondur", "Mutharam", "Ramadugu", "Thimmapur"],
        "Khammam": ["Enkoor", "Khammam", "Konijerla", "Madhira", "Mudigonda", "Nelakondapally", "Thallada", "Wyra", "Yerrupalem"],
        "Kumuram Bheem Asifabad": ["Asifabad", "Dahegaon", "Jainoor", "Kagaznagar", "Kerameri", "Sirpur"],
        "Mahabubabad": ["Dornakal", "Kesamudram", "Mahabubabad", "Narsimhulapet", "Thorrur"],
        "Mahabubnagar": ["Achampet", "Addakal", "Balanagar", "Bijinapally", "Devarkadra", "Jadcherla", "Kodangal", "Kosgi", "Mahabubnagar", "Makthal"],
        "Mancherial": ["Bellampalli", "Chennur", "Jaipur", "Luxettipet", "Mancherial", "Mandamarri", "Naspur"],
        "Medak": ["Andole", "Kulcharam", "Medak", "Narsapur", "Ramayampet", "Shankarampet", "Toopran"],
        "Medchal-Malkajgiri": ["Dundigal", "Ghatkesar", "Keesara", "Malkajgiri", "Medchal", "Quthbullapur", "Uppal"],
        "Mulugu": ["Eturnagaram", "Govindaraopet", "Mulugu", "Tadvai", "Venkatapur", "Wazeedu"],
        "Nagarkurnool": ["Achampet", "Bijinapally", "Kalwakurthy", "Kollapur", "Nagarkurnool", "Telkapally", "Uppununthala", "Vatwarlapally"],
        "Nalgonda": ["Alair", "Bhongir", "Choutuppal", "Devarakonda", "Huzurnagar", "Miryalaguda", "Nalgonda", "Nakrekal", "Ramannapeta", "Tripuraram", "Yadagirigutta"],
        "Narayanpet": ["Kosgi", "Maddur", "Maganur", "Narayanpet"],
        "Nirmal": ["Bhainsa", "Dilawarpur", "Khanapur", "Kubeer", "Mudhole", "Nirmal", "Sarangapur"],
        "Nizamabad": ["Armoor", "Balkonda", "Banswada", "Bodhan", "Dichpally", "Kamareddy", "Kotagiri", "Nizamabad", "Varni", "Yellareddy"],
        "Peddapalli": ["Godavarikhani", "Manthani", "Peddapalli", "Ramagiri", "Sultanabad"],
        "Rajanna Sircilla": ["Boinpally", "Cheriyal", "Gambhiraopet", "Koheda", "Mustabad", "Sircilla", "Vemulawada"],
        "Rangareddy": ["Chevella", "Farooqnagar", "Hayathnagar", "Maheshwaram", "Rajendranagar", "Shadnagar", "Shankarpally"],
        "Sangareddy": ["Andole", "Hathnoora", "Jogipet", "Kangti", "Kohir", "Narayankhed", "Patancheru", "Pulkal", "Sadasivpet", "Sangareddy", "Zaheerabad"],
        "Siddipet": ["Chinnakodur", "Dubbak", "Gajwel", "Husnabad", "Koheda", "Markook", "Siddipet", "Thoguta"],
        "Suryapet": ["Atmakur", "Chivvemla", "Huzurnagar", "Kodad", "Mothkur", "Nereducharla", "Suryapet", "Thirumalagiri"],
        "Vikarabad": ["Basheerabad", "Dharur", "Doma", "Kodangal", "Kulkacharla", "Marpalle", "Pargi", "Pudur", "Tandur", "Vikarabad"],
        "Wanaparthy": ["Atmakur", "Gopalpet", "Kothakota", "Pebbair", "Revally", "Wanaparthy"],
        "Warangal Rural": ["Bachannapet", "Cherial", "Dornakal", "Geesugonda", "Khanapur", "Maripeda", "Narsampet", "Parvathagiri", "Shayampet", "Wardhannapeta"],
        "Warangal Urban": ["Hanamkonda", "Kazipet", "Warangal"],
        "Yadadri Bhuvanagiri": ["Alair", "Bhuvanagiri", "Chityal", "Mothkur", "Rajapet", "Ramannapet", "Yadagirigutta"],
    },
    "Tripura": {
        "Dhalai": ["Ambassa", "Gandacherra", "Kulai", "Manu"],
        "Gomati": ["Amarpur", "Gomati", "Karbook", "Matabari", "Udaipur"],
        "Khowai": ["Khowai", "Teliamura"],
        "North Tripura": ["Dharmanagar", "Jampuijala", "Kadamtala", "Kanchanpur", "Panisagar"],
        "Sepahijala": ["Bishalgarh", "Jirania", "Majlishpur", "Sonamura"],
        "South Tripura": ["Bagafa", "Belonia", "Hrishyamukh", "Jolaibari", "Rajnagar", "Sabroom", "Santirbazar"],
        "Unakoti": ["Kailashahar", "Kumarghat", "Pencharthal"],
        "West Tripura": ["Agartala", "Bishalgarh", "Dukli", "Jirania", "Mohanpur", "Paschim"],
    },
    "Uttar Pradesh": {
        "Agra": ["Agra", "Bah", "Etmadpur", "Fatehabad", "Fatehpur Sikri", "Jagner", "Kheragarh", "Kiraoli", "Pinahat"],
        "Aligarh": ["Atrauli", "Aligarh", "Bijauli", "Gabhana", "Gangiri", "Iglas", "Jawan", "Khair", "Tappal"],
        "Allahabad": ["Allahabad", "Bara", "Chaka", "Handia", "Karchana", "Koraon", "Mauaima", "Meja", "Phulpur", "Pratappur", "Shankargarh", "Soraon"],
        "Ambedkar Nagar": ["Akbarpur", "Alapur", "Bhiyaon", "Jalal Pur", "Katehari", "Ram Nagar", "Tanda"],
        "Amethi": ["Amethi", "Bhadohi", "Gauriganj", "Jahangirganj", "Jagdishpur", "Musafirkhana", "Salon", "Sangrampur", "Shukulganj"],
        "Amroha": ["Amroha", "Dhanaura", "Gajraula", "Hasanpur", "Naugawan Sadat"],
        "Auraiya": ["Auraiya", "Ajitamal", "Bidhuna", "Dibiyapur", "Erwa Katra", "Sahar"],
        "Ayodhya": ["Ayodhya", "Bikapur", "Haidergarh", "Maya", "Milkipur", "Motipur", "Rudauli", "Sohawal", "Tanda"],
        "Azamgarh": ["Atraulia", "Azamgarh", "Burhanpur", "Didarganj", "Lalganj", "Mehnagar", "Nizamabad", "Phoolpur Pawai", "Sagri", "Tarwa"],
        "Baghpat": ["Baghpat", "Baraut", "Chhaprauli", "Khekra"],
        "Bahraich": ["Bahraich", "Balha", "Chittaura", "Fakharpur", "Huzoorpur", "Kaiserganj", "Mahasi", "Mihinpurwa", "Nanpara", "Nawabganj", "Payagpur", "Risia", "Shivpur", "Visheshwarganj"],
        "Ballia": ["Ballia", "Bansdih", "Bansipur", "Bairia", "Belhari", "Chilkahar", "Garwar", "Hanumanganj", "Maniyar", "Murli Chhapra", "Nagra", "Narhi", "Rasra", "Reoti", "Siar", "Sohaon"],
        "Balrampur": ["Balrampur", "Gainsari", "Gaisari", "Pachperwa", "Rehra Bazar", "Shravasti", "Tulsipur", "Utraula"],
        "Banda": ["Baberu", "Banda", "Bisanda", "Kamsin", "Kamasin", "Mahua", "Naraini", "Pailani", "Tindwari"],
        "Barabanki": ["Barabanki", "Dewa", "Fatehpur", "Haidergarh", "Haidargarh", "Masauli", "Nawabganj", "Ram Nagar", "Ramnagar", "Ramsanehighat", "Satrikh", "Siddhaur", "Sirauli", "Suratganj", "Trivediganj"],
        "Bareilly": ["Aonla", "Baheri", "Bithri Chainpur", "Faridpur", "Fatehganj West", "Meerganj", "Mirganj", "Nawabganj", "Richha", "Shergarh"],
        "Basti": ["Basti", "Gaur", "Harraiya", "Kaptanganj", "Kudaraha", "Mahadewa", "Rudhauli", "Saltaua", "Vikramjot", "Vijaynagaram"],
        "Bijnor": ["Afzalgarh", "Bijnor", "Chandpur", "Dhampur", "Haldaur", "Kiratpur", "Kotwali", "Mandawar", "Nagina", "Najibabad", "Noorpur", "Seohara", "Sherkot"],
        "Budaun": ["Bisauli", "Budaun", "Dataganj", "Gunnaur", "Island", "Kakrala", "Kampil", "Qadar Chowk", "Sahaswan", "Samrer", "Shedpur", "Usawan", "Wazirganj"],
        "Bulandshahr": ["Agauta", "Auras", "Bulandshahr", "Debai", "Gulaothi", "Jahangirabad", "Khurja", "Lakhaoti", "Pahasu", "Shikarpur", "Siana", "Siyana", "Sikandrabad", "Unchagaon"],
        "Chandauli": ["Chandauli", "Chakiya", "Dhanapur", "Mughal Sarai", "Niyamatabad", "Sakaldeeha", "Sakaldiha"],
        "Chitrakoot": ["Chitrakoot", "Karchha", "Manikpur", "Mau", "Pahadi", "Ramnagar"],
        "Deoria": ["Baitalghat", "Barhaj", "Bhatpar Rani", "Deoria", "Lar", "Pathardeua", "Rampur Karkhana", "Rudrapur", "Salempur"],
        "Etah": ["Aliganj", "Awagarh", "Etah", "Jalesar", "Jaithara", "Kasganj", "Marhara", "Patiyali", "Saket"],
        "Etawah": ["Bakewar", "Basrehar", "Bharthana", "Etawah", "Jaswantnagar", "Saifai"],
        "Farrukhabad": ["Amritpur", "Farrukhabad", "Fatehgarh", "Kaimganj", "Kayamganj", "Mohammadabad", "Shamsabad"],
        "Fatehpur": ["Amauli", "Bindki", "Dhata", "Fatehpur", "Hathgaon", "Haswa", "Khaga", "Malwan", "Talgram", "Teliani", "Vijayipura"],
        "Firozabad": ["Firozabad", "Jasrana", "Narkhi", "Shikohabad", "Sirsaganj", "Tundla"],
        "Gautam Buddha Nagar": ["Dadri", "Dankaur", "Jewar", "Noida"],
        "Ghaziabad": ["Ghaziabad", "Hapur", "Loni", "Modinagar", "Muradnagar", "Tronica City"],
        "Ghazipur": ["Ghazipur", "Jangipur", "Karanda", "Kasimabad", "Muhammadabad", "Sadat", "Saidpur", "Zamania"],
        "Gonda": ["Colonelganj", "Gonda", "Katra Bazar", "Mankapur", "Mujehna", "Nawabganj", "Paraspur", "Tarabganj", "Umri"],
        "Gorakhpur": ["Bansgaon", "Bhathat", "Campierganj", "Chauri Chaura", "Gorakhpur", "Gola", "Jungle Kaudia", "Khajani", "Nichlaul", "Pipiganj", "Sardar Nagar"],
        "Hamirpur": ["Hamirpur", "Maudaha", "Muskara", "Rath", "Sarila", "Sumerpur"],
        "Hapur": ["Dhaulana", "Garh Muktesar", "Hapur", "Pilkhuwa"],
        "Hardoi": ["Ahirori", "Alwan", "Bilgram", "Hardoi", "Kachhauna", "Madhoganj", "Mallanwan", "Palia", "Sanda", "Sandila", "Shahabad", "Sawayajpur", "Sursa"],
        "Hathras": ["Hathras", "Mursan", "Sasni", "Sadabad"],
        "Jalaun": ["Jalaun", "Kalpi", "Konch", "Mahoba", "Madhogarh", "Orai", "Ramnagar"],
        "Jaunpur": ["Badlapur", "Barsathi", "Dobhi", "Jaunpur", "Kerakat", "Machhlishahr", "Mungra Badshahpur", "Shahganj", "Sikandarpur", "Sirkoni"],
        "Jhansi": ["Babina", "Bangra", "Chirgaon", "Garautha", "Jhansi", "Mahroni", "Mauranipur", "Moth"],
        "Kannauj": ["Chhibramau", "Gursahaiganj", "Kannauj", "Saraimer", "Talgram", "Tirwa", "Umarda"],
        "Kanpur Dehat": ["Akbarpur", "Bhognipur", "Derapur", "Ghatampur", "Jhinjhak", "Maholi", "Rajpur", "Rasulabad", "Sarsaul"],
        "Kanpur Nagar": ["Bilhaur", "Kanpur", "Shivrajpur"],
        "Kasganj": ["Amanpur", "Ganjdundwara", "Kasganj", "Patiyali", "Sahawar", "Soron"],
        "Kaushambi": ["Chail", "Kaushambi", "Manjhanpur", "Saini", "Sirathu"],
        "Kheri": ["Bhira", "Dhaurahra", "Gola Gokarnath", "Hargaon", "Isanagar", "Kasta", "Lakhimpur", "Mitauli", "Mohammdi", "Nighasan", "Paila", "Palia Kalan", "Paseha", "Phool Bhehar", "Ramia Behar", "Sandilana"],
        "Kushinagar": ["Fazilnagar", "Hata", "Kasya", "Khadda", "Kushinagar", "Padrauna", "Ramkola", "Sewarahi", "Tamkuhi Raj", "Vishnupura"],
        "Lalitpur": ["Birdha", "Lalitpur", "Madawara", "Mehroni", "Talbehat"],
        "Lucknow": ["Bakshi Ka Talab", "Chinhat", "Lucknow", "Malihabad", "Mohanlalganj", "Sarojini Nagar"],
        "Maharajganj": ["Bridgmanganj", "Dhani", "Farenda", "Ghughuli", "Maharajganj", "Mitwal", "Nautanwa", "Nichlaul", "Paniyara", "Pharenda", "Siswa Bazar"],
        "Mahoba": ["Charkhari", "Kulpahar", "Mahoba", "Panwari"],
        "Mainpuri": ["Bhongaon", "Karhal", "Kishni", "Kuraoli", "Mainpuri", "Sultanganj"],
        "Mathura": ["Baldeo", "Chhata", "Farah", "Govardhan", "Mathura", "Mat", "Mant", "Nandgaon", "Nohjhil", "Raya"],
        "Mau": ["Ghosi", "Kopaganj", "Mau", "Madhuban", "Muhammadabad", "Phephna", "Ratanpura"],
        "Meerut": ["Hapur", "Kharkhauda", "Meerut", "Mawana", "Modinagar", "Rohta", "Sardhana"],
        "Mirzapur": ["Chunar", "Hallia", "Jamalpur", "Lalganj", "Marihan", "Mirzapur", "Meja", "Rajgarh", "Sikharpur"],
        "Moradabad": ["Amroha", "Bilari", "Kanth", "Moradabad", "Mundapandey", "Thakurdwara"],
        "Muzaffarnagar": ["Budhana", "Charthawal", "Jansath", "Kairana", "Khatoli", "Khatauli", "Mirpur", "Muzaffarnagar", "Purkazi", "Shahpur"],
        "Pilibhit": ["Amariya", "Barkhera", "Bisalpur", "Marori", "Pilibhit", "Puranpur"],
        "Pratapgarh": ["Babaganj", "Kunda", "Lalganj", "Mandhata", "Patti", "Pratapgarh", "Rampur Khas", "Raniganj", "Sangramgarh"],
        "Prayagraj": ["Allahabad", "Bara", "Chaka", "Handia", "Karchana", "Koraon", "Mauaima", "Meja", "Phulpur", "Pratappur", "Shankargarh", "Soraon"],
        "Rae Bareli": ["Dalmau", "Gauriganj", "Lalganj", "Mahrajganj", "Rahi", "Rae Bareli", "Salon", "Sareni", "Shivgarh", "Tiloi", "Unchahar"],
        "Rampur": ["Bilaspur", "Milak", "Rampur", "Shahabad", "Suar", "Tanda"],
        "Saharanpur": ["Behat", "Deoband", "Gangoh", "Nanauta", "Rampur Maniharan", "Saharanpur", "Sarsawa"],
        "Sambhal": ["Asmoli", "Bahjoi", "Baniyakhera", "Gunnaur", "Pawasa", "Sambhal", "Suar"],
        "Sant Kabir Nagar": ["Baghauli", "Bhaupar", "Hainsar Bazar", "Khalilabad", "Mehdawal", "Santha"],
        "Shahjahanpur": ["Jaitpur", "Katra", "Khudaganj", "Mirzapur", "Powayan", "Shahjahanpur", "Sindhauli", "Tilhar"],
        "Shamli": ["Budhana", "Jhinjhana", "Kairana", "Kandhla", "Shamli", "Thana Bhawan", "Un"],
        "Shravasti": ["Bhinga", "Gisrawan", "Ikauna", "Jamunaha", "Sirsiya", "Sravan"],
        "Siddharthnagar": ["Bansi", "Barhni", "Domariyaganj", "Itwa", "Khesraha", "Shohratgarh", "Uska", "Uska Bazar"],
        "Sitapur": ["Biswan", "Hargaon", "Kasmanda", "Laharpur", "Mahmudabad", "Maholi", "Misrikh", "Pahala", "Rampur Mathura", "Reusa", "Sakran", "Sitapur"],
        "Sonbhadra": ["Chopan", "Dudhi", "Ghorawal", "Myorpur", "Nagwa", "Obra", "Robertsganj"],
        "Sultanpur": ["Akhand Nagar", "Amethi", "Baldirai", "Dostpur", "Dubeypur", "Kadipur", "Kurwar", "Lambhua", "Motigarpur", "Sultanpur"],
        "Unnao": ["Asoha", "Bangarmau", "Bighapur", "Fatehpur Chaurasi", "Ganj Muradabad", "Hasanganj", "Hilouli", "Mohan", "Nawabganj", "Purwa", "Safipur", "Sikandarpur Saraosi", "Unnao"],
        "Varanasi": ["Arajiline", "Cholapur", "Harahua", "Kashi Vidyapeeth", "Pindra", "Rohaniya", "Sewapuri", "Varanasi"],
    },
    "Uttarakhand": {
        "Almora": ["Almora", "Bhainsiyachhana", "Bhikiyasain", "Chaukhutia", "Dhauladevi", "Dwarahat", "Hawalbag", "Lamgara", "Ranikhet", "Salt", "Sult", "Syaldeh", "Tarikhet"],
        "Bageshwar": ["Bageshwar", "Kapkot", "Garud"],
        "Chamoli": ["Chamoli", "Dasholi", "Dewal", "Gairsain", "Ghatt", "Joshimath", "Karnaprayag", "Narayanbagar", "Pokhari", "Tharali"],
        "Champawat": ["Barakot", "Champawat", "Lohaghat", "Pati"],
        "Dehradun": ["Chakrata", "Dehradun", "Doiwala", "Kalsi", "Rishikesh", "Sahaspur", "Tiuni", "Vikasnagar"],
        "Haridwar": ["Bahadrabad", "Bhagwanpur", "Haridwar", "Laksar", "Narsan", "Roorkee"],
        "Nainital": ["Betalghat", "Dhari", "Haldwani", "Kotabagh", "Nainital", "Okhalkanda", "Ramgarh", "Ramnagar"],
        "Pauri Garhwal": ["Bironkhal", "Dwarikhal", "Ekeshwar", "Jahrikhal", "Kaljikhal", "Khirsu", "Kot", "Lansdowne", "Nainidanda", "Pauri", "Pabo", "Paukhal", "Pokhara", "Rikhnikhal", "Thalisain", "Yamkeshwar"],
        "Pithoragarh": ["Berinag", "Dharchula", "Didihat", "Gangolihat", "Kanalichhina", "Munsiyari", "Pithoragarh"],
        "Rudraprayag": ["Augustmuni", "Jakholi", "Kedarnath", "Rudraprayag", "Ukhimath"],
        "Tehri Garhwal": ["Chamba", "Deoprayag", "Devprayag", "Jakhnidhar", "Narendra Nagar", "Pratapnagar", "Tehri", "Thatyur"],
        "Udham Singh Nagar": ["Bazpur", "Gadarpur", "Jaspur", "Kashipur", "Khatima", "Kichha", "Nanak Matta", "Rudrapur", "Sitarganj"],
        "Uttarkashi": ["Bhatwari", "Chinyalisaur", "Dunda", "Mori", "Naugaon", "Purola"],
    },
    "West Bengal": {
        "Alipurduar": ["Alipurduar", "Falakata", "Kalchini", "Kumargram", "Madarihat"],
        "Bankura": ["Bankura", "Barjora", "Bishnupur", "Chhatna", "Gangajalghati", "Indpur", "Indus", "Joypur", "Khatra", "Kotulpur", "Mejia", "Onda", "Raipur", "Saltora", "Simlapal", "Sonamukhi", "Sarenga", "Taldangra"],
        "Birbhum": ["Bolpur", "Dubrajpur", "Khoyrasole", "Labpur", "Labhpur", "Mohammed Bazar", "Murarai", "Nalhati", "Nanoor", "Rampurhat", "Rajnagar", "Sainthia", "Siuri"],
        "Cooch Behar": ["Cooch Behar", "Dinhata", "Mathabhanga", "Mekhliganj", "Sitai", "Sitalkuchi", "Tufanganj"],
        "Dakshin Dinajpur": ["Balurghat", "Bansihari", "Buniadpur", "Cumarsole", "Gangarampur", "Harirampur", "Kushmandi", "Tapan"],
        "Darjeeling": ["Darjeeling", "Jorebunglow Sukhiapokhri", "Kalimpong", "Kurseong", "Mirik", "Siliguri"],
        "Hooghly": ["Arambagh", "Balagarh", "Chanditala", "Chandannagar", "Dhanekhali", "Goghat", "Haripal", "Jangipara", "Khanakul", "Pandua", "Polba-Dadpur", "Pursura", "Serampore", "Singur", "Tarakeswar"],
        "Howrah": ["Amta", "Bagnan", "Bally", "Domjur", "Jagatballavpur", "Panchla", "Sankrail", "Shyampur", "Uluberia"],
        "Jalpaiguri": ["Dhupguri", "Jalpaiguri", "Kalchini", "Kranti", "Mal", "Maynaguri", "Nagrakata", "Rajganj"],
        "Jhargram": ["Binpur", "Gopiballavpur", "Jamboni", "Jhargram", "Nayagram", "Sankrail"],
        "Kalimpong": ["Gorubathan", "Kalimpong"],
        "Kolkata": ["Kolkata"],
        "Malda": ["Bamangola", "Chanchal", "English Bazar", "Gazole", "Harishchandrapur", "Kaliachak", "Manikchak", "Moti", "Old Malda", "Ratua"],
        "Murshidabad": ["Baharampur", "Beldanga", "Bharatpur", "Burwan", "Domkal", "Farakka", "Hariharpara", "Jalangi", "Kandi", "Khargram", "Lalgola", "Murshidabad", "Nabagram", "Nowda", "Raghunathganj", "Raninagar", "Rejinagar", "Samserganj", "Sagardighi", "Suti"],
        "Nadia": ["Chapra", "Chakdaha", "Haringhata", "Hanskhali", "Karimpur", "Krishnaganj", "Krishnanagar", "Nakashipara", "Ranaghat", "Santipur", "Tehatta"],
        "North 24 Parganas": ["Amdanga", "Baduria", "Bagdah", "Barasat", "Basirhat", "Bongaon", "Deganga", "Gaighata", "Habra", "Haroa", "Hingalganj", "Minakhan", "Rajarhat", "Swarupnagar", "Sandeshkhali"],
        "Paschim Bardhaman": ["Asansol", "Barabani", "Durgapur", "Faridpur", "Jamuria", "Kanksa", "Ondal", "Pandabeswar", "Raniganj", "Salanpur"],
        "Paschim Medinipur": ["Binpur", "Chandrakona", "Daspur", "Debra", "Ghatal", "Garbeta", "Keshpur", "Kharagpur", "Narayangarh", "Sabang", "Sankrail", "Salboni"],
        "Purba Bardhaman": ["Bhatar", "Burdwan", "Ausgram", "Galsi", "Jamalpur", "Kalna", "Katwa", "Ketugram", "Manteswar", "Memari", "Raina"],
        "Purba Medinipur": ["Bhagabanpur", "Contai", "Deshapran", "Egra", "Haldia", "Kanthi", "Mahishadal", "Nandigram", "Panskura", "Ramnagar", "Tamluk"],
        "Purulia": ["Arsha", "Baghmundi", "Balarampur", "Bandwan", "Barabazar", "Hura", "Jaipur", "Jhalda", "Kashipur", "Manbazar", "Puncha", "Purulia", "Para", "Raghunathpur", "Santuri"],
        "South 24 Parganas": ["Baruipur", "Basanti", "Bhangore", "Bishnupur", "Budge Budge", "Canning", "Diamond Harbour", "Gosaba", "Jaynagar", "Kakdwip", "Kultali", "Magrahat", "Mandirbazar", "Mathurapur", "Namkhana", "Patharpratima", "Sagar"],
        "Uttar Dinajpur": ["Chopra", "Dalkhola", "Goalpokhar", "Hemtabad", "Islampur", "Itahar", "Karandighi", "Raiganj"],
    },
    "Andaman and Nicobar Islands": {
        "Nicobar": ["Car Nicobar", "Nancowry"],
        "North and Middle Andaman": ["Diglipur", "Mayabunder", "Rangat"],
        "South Andaman": ["Ferrargunj", "Port Blair"],
    },
    "Chandigarh": {
        "Chandigarh": ["Chandigarh"],
    },
    "Dadra and Nagar Haveli and Daman and Diu": {
        "Dadra and Nagar Haveli": ["Dadra", "Nagar Haveli", "Silvassa"],
        "Daman": ["Daman", "Diu"],
    },
    "Delhi": {
        "Central Delhi": ["Connaught Place", "Daryaganj", "Karol Bagh", "Paharganj"],
        "East Delhi": ["Gandhi Nagar", "Patparganj", "Preet Vihar", "Vivek Vihar"],
        "New Delhi": ["Chanakyapuri", "New Delhi"],
        "North Delhi": ["Civil Lines", "Kotwali", "Model Town", "Sadar Bazar", "Subzi Mandi"],
        "North East Delhi": ["Nand Nagri", "Seema Puri", "Seelampur", "Shahdara"],
        "North West Delhi": ["Alipur", "Bawana", "Kanjhawala", "Narela", "Rohini"],
        "Shahdara": ["Dilshad Garden", "Geeta Colony", "Jhilmil", "Shahdara"],
        "South Delhi": ["Hauz Khas", "Kalkaji", "Malviya Nagar", "Mehrauli", "Saket"],
        "South East Delhi": ["Badarpur", "Lajpat Nagar", "Okhla", "Tughlakabad"],
        "South West Delhi": ["Dwarka", "Najafgarh", "Uttam Nagar"],
        "West Delhi": ["Janakpuri", "Moti Nagar", "Paschim Vihar", "Punjabi Bagh", "Rajouri Garden"],
    },
    "Jammu and Kashmir": {
        "Anantnag": ["Anantnag", "Bijbehara", "Dooru", "Pahalgam", "Shangus", "Shangus"],
        "Bandipora": ["Bandipora", "Gurez", "Sonawari"],
        "Baramulla": ["Baramulla", "Boniyar", "Kreeri", "Pattan", "Rafiabad", "Sopore", "Uri"],
        "Budgam": ["Beerwah", "Budgam", "Chadoora", "Charar-i-Sharief", "Khansahib", "Nagam"],
        "Doda": ["Bhaderwah", "Bhalla", "Doda", "Thathri"],
        "Ganderbal": ["Ganderbal", "Kangan", "Lar", "Safapora"],
        "Jammu": ["Akhnoor", "Bishnah", "Jammu", "Khour", "Marh", "Nagrota", "Ranbir Singh Pura", "Suchetgarh"],
        "Kathua": ["Billawar", "Basohli", "Hiranagar", "Kathua", "Mahanpur", "Marheen"],
        "Kishtwar": ["Chatroo", "Dachhan", "Kishtwar", "Marwah", "Padder"],
        "Kulgam": ["Devsar", "D H Pora", "Kulgam", "Qazigund"],
        "Kupwara": ["Drugmulla", "Handwara", "Karnah", "Kupwara", "Lolab", "Sogam"],
        "Poonch": ["Haveli", "Mendhar", "Poonch", "Surankote"],
        "Pulwama": ["Aripal", "Awantipora", "Pampore", "Pulwama", "Tral"],
        "Rajouri": ["Budhal", "Darhal", "Kalakote", "Manjakote", "Nowshera", "Rajouri", "Sundarbani", "Thannamandi"],
        "Ramban": ["Banihal", "Gool", "Ramban", "Ukhral"],
        "Reasi": ["Gulabgarh", "Mahore", "Reasi", "Shri Mata Vaishno Devi"],
        "Samba": ["Purmandal", "Ramgarh", "Samba", "Vijaypur"],
        "Shopian": ["Kellar", "Shopian", "Zainpora"],
        "Srinagar": ["Eidgah", "Khanyar", "Pantha Chowk", "Shalteng", "Srinagar"],
        "Udhampur": ["Chenani", "Dudu Basantgarh", "Majalta", "Ramnagar", "Udhampur"],
    },
    "Ladakh": {
        "Kargil": ["Drass", "Kargil", "Sankoo", "Shakar Chiktan", "Zanskar"],
        "Leh": ["Chushul", "Durbuk", "Leh", "Nubra", "Nyoma", "Panamic", "Samad Rokchen", "Tangtse"],
    },
    "Lakshadweep": {
        "Lakshadweep": ["Agatti", "Amini", "Andrott", "Bitra", "Chetlat", "Kadmat", "Kalpeni", "Kavaratti", "Kiltan", "Minicoy"],
    },
    "Puducherry": {
        "Karaikal": ["Karaikal", "Nedungadu", "Thirunallar"],
        "Mahe": ["Mahe"],
        "Puducherry": ["Ariankuppam", "Bahour", "Mannadipet", "Nettapakkam", "Oulgaret", "Puducherry", "Villianur"],
        "Yanam": ["Yanam"],
    },
}

export const STATES = Object.keys(INDIA_LOCATION_DATA).sort()

export function getDistricts(state: string): string[] {
    if (!state || !INDIA_LOCATION_DATA[state]) return []
    return Object.keys(INDIA_LOCATION_DATA[state]).sort()
}

export function getSubDistricts(state: string, district: string): string[] {
    if (!state || !district) return []
    const districtData = INDIA_LOCATION_DATA[state]?.[district]
    if (!districtData) return []
    // Filter out any nested arrays that may have been accidentally added
    return districtData.filter((item): item is string => typeof item === "string").sort()
}